// ******************************************************************************************************
// *            Inverter.h
// ******************************************************************************************************
// ******************************************************************************************************
// *
// * This information is proprietary to Eaton  
// *
// ******************************************************************************************************
// *
// *  Copyright (c) 2008 Eaton
// *    ALL RIGHTS RESERVED
// *
// ******************************************************************************************************
// ******************************************************************************************************
// *    FILE NAME: Inverter.h
// *
// *    DESCRIPTION: 
// *
// *    ORIGINATOR: Kevin VanEyll
// *
// *    DATE: 2/8/2010
// *
// *    HISTORY: See Subversion history.
// ******************************************************************************************************
#ifndef _INVERTER_H
#define _INVERTER_H

#include "Constants.h"
#include "algos.h"
#include "SineReference.h"
#include "Eeprom_Map.h"
#include "StateTimer.h"
#include "InvSync.h"
#include "FilteredBit.h"
#include "NB_Config.h"
#include "Fir.h"

#define GL_UTILITY_LOSS_TRANSIENT_10_SEC        12500 //10s = 12500/1.25K
#define INVETER_MIN_FREQ 45		//45Hz:byp min:46Hz, add 1Hz hysteria
#define TDead_Ramp_Step 	0.00162f		

typedef struct
{
    uint16_t InverterOn             : 1;
    uint16_t InverterOpenLoop       : 1;
    uint16_t VoltageRMSLoopOn       : 1;
    uint16_t MatchBypassRMS         : 1;

    uint16_t OutputShort            : 1;    // True if software current is furthur limited by output short conditions
    uint16_t SoftwareCurrentLimited : 1;    // True if the inverter current command was software limited anytime in the last line cycle.
    uint16_t ECTCurrentLoop         : 1;    // Yanming 20100903 add for ECT
    uint16_t CurrentRMSLoopOn       : 1;    // Yanming 20101008 add for ECT

    uint16_t BypassMatched          : 1;
    uint16_t UseResonantComp        : 1;
    uint16_t UseDynamicRCGains      : 1;
    uint16_t DischargeCaps          : 1;

    uint16_t InverterOnFromSuspend  : 1;
//		uint16_t unused13_15			: 3;
	uint16_t LoadShareDCFFB0Tune	: 1;	//for jira wombat473 Vin127v~147v loadshare
	uint16_t THDiImprove			: 1;
	uint16_t unused15				: 1;
    
    uint16_t word1placeholder;
    uint16_t word2placeholder;
    uint16_t /*unused*/: 12;
    uint16_t SequenceNumber: 4;
} stInverterStatus;

typedef union
{
    stInverterStatus    bit;
    uint16_t            all;
    uint16_t            words[sizeof(stInverterStatus)];
} uInverterStatus;

enum inv_slew_rate_t
{
    SLEW_RATE_PAR = 0,              // 20kHz update rate
    SLEW_RATE_1_HZ,                 // 20kHz update rate
    SLEW_RATE_3_HZ,                 // 20kHz update rate
    SLEW_RATE_5_HZ,                 // 20kHz update rate
    SLEW_RATE_7_HZ,                 // 20kHz update rate
    INV_MAX_SLEW_RATE
};

struct stSlewRateLimits
{
    float   PhaseGain;
    float   PhaseLimit;
    float   FrequencyGain;
    float   FrequencyLimit;
};

namespace
{
//  float InverterTs = 0.000049;        //Zhangjun/20111206,delete
//  float InverterTs = 0.000098;        //Zhangjun/20111206,add

    //
    // Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
    // Generated by MATLAB(R) 7.8 and the Signal Processing Toolbox 6.11.
    // Generated on: 26-Apr-2011 15:42:40
    //
    // low-pass FIR filter, idea is to remove the fundamental ripple in the power, and provide
    // up front filtering for PD controller to remove high frequency component, which will
    // make PD control unstable. Over-damped step response is required, no ringing.
    // 
    // parameters:  Taylor Window FIR. Fs = 1250 Hz.
    //              number of sidelobes ( Nbar ) = 4
    //              side lobe level = -50dB
    //              Fs = 1125 Hz
    //              Fc = 15 Hz
    //              order = 36
    //

    const float ActiveTable[37] = {
        0.002531216713, 0.003160460852, 0.004339175299, 0.006090017967, 0.008408660069,
        0.01126558054,  0.01460920274,  0.01836929843,  0.02245973423,  0.02678008564,
        0.03121625073,  0.03564078733,  0.03991407901,  0.04388745129,  0.04740897939,
        0.05033203959,  0.05252591893,  0.05388692394,  0.05434828252,  0.05388692394,
        0.05252591893,  0.05033203959,  0.04740897939,  0.04388745129,  0.03991407901,
        0.03564078733,  0.03121625073,  0.02678008564,  0.02245973423,  0.01836929843,
        0.01460920274,  0.01126558054,  0.008408660069, 0.006090017967, 0.004339175299,
        0.003160460852, 0.002531216713
    };


}

enum INV_LEG_ON
{
    CAL_INV_All_ON = 0,              //three leg all on
	CAL_INV_LEG_A_ON   = 1, 			 //leg a
	CAL_INV_LEG_B_ON   = 2, 			 
	CAL_INV_LEG_C_ON   = 3

};

extern const float InverterTs_HV;
extern float InverterTs;
extern const float Capacitance_INV20K;
extern const float Capacitance_INV40K;

extern uint16_t InvHWCurrentLimit;
extern uint16_t InvHWCurrentLimitReal;
extern float  InverterCap;
extern uint16_t LoopCoeffiIndex;

class InverterControl
{
    public:
        InverterControl( void ) 
            : Locked( PASS_16, PASS_4 ), 
              SineRef( NOM_FREQUENCY_60HZ, InverterTs ),
              ActivePowerFilter( ActiveTable ), 
              ReactivePowerFilter( ActiveTable ) 
        {
            ParallelRMSDownSample = 2;
            MasterRMSData.phA = 0;
            MasterRMSData.phB = 0;
            MasterRMSData.phC = 0;
            SyncSource = NULL;
            ECTPFAngle = 0;
            ECTPFAngleTemp = 0;
            SlewRate = SLEW_RATE_PAR;
            ActivePowerFiltered = 0.0f;
            ReactivePowerFiltered = 0.0f;
            PeakVoltage          = float(230.0f * SQRT_2);
//	            PeakVoltageLL        = float(PeakVoltage * SQRT_3);

        }
        ~InverterControl()
        {
        }

        friend class Debugger;
        
    public:
        void RunPLLFast( void );
        void PLLPeriodicFunction( void );

        void ParametersInit( void );
        void Run_ISR( void );
        void InverterLineCycleTask( void );
        void On( void );
        void OnFromESS(void);
        void OnOpenLoop( void );
        void Off( void );
        void OnOpenLoop_FCT( void );
        void DischargeCaps( void );
        void Off_FCT( void );
        void SetSWCurrentLimit(float limit);
        void SetInverterVoltage( uint16_t voltage );
        void SetHWCurrentLimit( int16_t currentLimit );
        void EEFunc_Inverter( const EE_ID* ee, const uint16_t* data );
        bool ValidInverterVoltage( uint16_t voltage );
        void SetMasterRMSData( int16_t pA, int16_t pB, int16_t pC );
        void SetSyncSource( sync_states_t state );
        void SetECTPowerfactor( uint16_t powerfactor );
		void SetECTPowerAndPf( uint16_t power, uint16_t powerfactor );
        void OnECTCurrentLoop( void );
        void UpdateECTCurrentRef( void );
        void ParallelSystemSelectiveTrip(void);
        void StartFixedDuty( int16_t duty );

        void EnableRMS( void )
        {
            InverterStatus.bit.VoltageRMSLoopOn = 1;
        }
        void DisableRMS( void )
        {
            InverterStatus.bit.VoltageRMSLoopOn = 0;
        }
        
        void MatchBypassVoltage( bool onoff )
        {
        	if ( !MatchBypassForced )	//alway false:
        	{
                if (onoff)
                {
                    InverterStatus.bit.MatchBypassRMS = 1;
                }
                else
                {
                    InverterStatus.bit.MatchBypassRMS = 0;
                }
            }
            else
            {
                if (onoff)
                {
                    StoredBypassMatchState = 1;
                }
                else
                {
                    StoredBypassMatchState = 0;
                }
            }
        }

        const uInverterStatus& GetStatus( void )
        {
            return InverterStatus;
        }
        
        const float& DefaultSWCurrentLimit(void)
        {
//	            return ee_DefaultSWCurrentLimit;
        }

        bool IsPhaseLocked( void )
        {
            return Locked.GetState();
        }
        const stThreePhase* GetMasterRMSData( void )
        {   return &MasterRMSData;                          }
        float GetPhaseError( void )
        {   return PhaseError;                              }
        bool IsMatchedBypass( void )
        {   return InverterStatus.bit.BypassMatched;        }
        float GetAngle( void )
        {   return SineRef.Angle;                           }
        float GetFrequency( void )                          
        {   return SineRef.Frequency;                       }
        const stThreePhase& GetLoadShareVoltageCal( void )
        {   return ee_LoadShareVoltageCal;                  }                   
        const SineReference* GetSyncSource( void )
        {   return SyncSource;                              }
        
        void SetSoftwareCurrentLimit( float limit )
        {
            CriticalSection enter;
//	            SoftwareCurrentLimit = limit;
        }
        const stThreePhase& GetDCOffset( void )             {   return InverterDCOffset;                        }		

        // Puck/20140107, add for debug
        stFirstOrderIIRFP  GetInverterVRMSGains( void )
        {
        	return InverterVRMSGainsA;
        }

        void SetInverterVRMSGains( stFirstOrderIIRFP * coefficients )
        {
            InverterVRMSGainsA = *coefficients;
            InverterVRMSGainsB = InverterVRMSGainsA;
            InverterVRMSGainsC = InverterVRMSGainsA;
	
            VRMSSatFactor = 1.0 / ( InverterVRMSGainsA.B1 - InverterVRMSGainsA.A1 );
        }

        stSecondOrderIIRFP  GetInverterVGains1( void )
        {
            return InverterVGainsA;
        }

        void SetInverterVGains1( stSecondOrderIIRFP * coefficients )
        {
            InverterVGainsA = *coefficients;
            InverterVGainsB = InverterVGainsA;  
            InverterVGainsC = InverterVGainsA;  

            InverterVSatFactorNew = 1.0f / ( ( InverterVGainsA.B1 + InverterVGainsA.B2 ) - ( InverterVGainsA.A1 + InverterVGainsA.A2 ) );
        }

        stSecondOrderIIRFP  GetInverterVGains2( void )
        {
            stSecondOrderIIRFP result = InverterVGainsA2;
           // result.B0 = result.B0 * VoltageNormFactor / CurrentNormFactor;
            return result;
        }

        void SetInverterVGains2( stSecondOrderIIRFP * coefficients )
        {
            InverterVGainsA2 = *coefficients;
           // InverterVGainsA2.B0 = ( InverterVGainsA2.B0 / VoltageNormFactor ) * CurrentNormFactor;
            InverterVGainsB2 = InverterVGainsA2;
            InverterVGainsC2 = InverterVGainsA2;

            InverterVSatFactorNew2 = 1.0f / ( ( InverterVGainsA2.B1 + InverterVGainsA2.B2 ) - ( InverterVGainsA2.A1 + InverterVGainsA2.A2 ) );
        }

        stSecondOrderIIRFP  GetInverterIGains( void )
        {
            stSecondOrderIIRFP result = InverterIGainsA;
            result.B0 = result.B0 * CurrentNormFactor;
            return result;
        }

        void SetInverterIGains( stSecondOrderIIRFP * coefficients )
        {
            InverterIGainsA = *coefficients;
            InverterIGainsA.B0 = InverterIGainsA.B0 / CurrentNormFactor;
            InverterIGainsB = InverterIGainsA;
            InverterIGainsC = InverterIGainsA;

			InverterISatFactorNew = 1.0f / ((InverterIGainsA.B1 + InverterIGainsA.B2) - (InverterIGainsA.A1 + InverterIGainsA.A2 ));
        }

        stSecondOrderIIRFP  GetInverterDCCompensator( void )
        {
            return InverterDCCompensatorA;
        }

        void SetInverterDCCompensator( stSecondOrderIIRFP * coefficients )
        {
            InverterDCCompensatorA = *coefficients;
            InverterDCCompensatorB = InverterDCCompensatorA;  //Puck/20120214, modify
            InverterDCCompensatorC = InverterDCCompensatorA;  //Puck/20120214, modify
        }

		//1.1. LoadShareDroopTable
        stFirstOrderIIRFP  GetLoadShareDroopTable( void )
        {
            return LoadShareDroopTable;
        }

        void SetLoadShareDroopTable( stFirstOrderIIRFP * coefficients )
        {
            LoadShareDroopTable = *coefficients;
        }

		//1.2 ReactiveLoadShareDroopTable
		stFirstOrderIIRFP	GetReactiveLoadShareDroopTable( void )
		{
			return ReactiveLoadShareDroopTable;

		}

		void SetReactiveLoadShareDroopTable( stFirstOrderIIRFP * coefficients )
		{
			ReactiveLoadShareDroopTable = *coefficients;
		}
		
		//1.3 ReactivePowerDroopTable
		stFirstOrderIIRFP	GetReactivePowerDroopTable( void )
		{
			return ReactivePowerDroopTable;

		}

		void SetReactivePowerDroopTable( stFirstOrderIIRFP * coefficients )
		{
			ReactivePowerDroopTable = *coefficients;
		}

		//1.4. LoadShareDCFeedForwardTable
		stFirstOrderIIRFP  GetLoadShareDCFeedForwardTable( void )
		{
			return LoadShareDCFeedForwardTable;
	
		}
	
		void SetLoadShareDCFeedForwardTable( stFirstOrderIIRFP * coefficients )
		{
			LoadShareDCFeedForwardTable = *coefficients;
		}

		//1.5 HighDCVPhaseDroopTable
		stSecondOrderIIRFP	GetHighDCVPhaseDroopTable( void )
		{
			return HighDCVPhaseDroopTable;

		}

		void SetHighDCVPhaseDroopTable( stSecondOrderIIRFP * coefficients )
		{
			HighDCVPhaseDroopTable = *coefficients;
		}



        stFirstOrderIIRFP  GetECTPowerGains( void )
        {
            return ECTPowerGains;
        }

        void SetECTPowerGains( stFirstOrderIIRFP * coefficients )
        {
            ECTPowerGains = *coefficients;
        }

        stFirstOrderIIRFP  GetECTInverterIGains( void )
        {
            stFirstOrderIIRFP result = ECTInverterIGainsA;
            result.B0 = result.B0 * CurrentNormFactor;
            return result;
        }

        void SetECTInverterIGains( stFirstOrderIIRFP * coefficients )
        {
            ECTInverterIGainsA = *coefficients;
            ECTInverterIGainsA.B0 = ECTInverterIGainsA.B0 / CurrentNormFactor;
            ECTInverterIGainsB = ECTInverterIGainsA;
            ECTInverterIGainsC = ECTInverterIGainsA;
        }
		
        void SetTHDiImprove( bool bit)
        {
			InverterStatus.bit.THDiImprove = bit;
        }
		
    public:
        float               InverterUVAlarmSetLevel;
        float               InverterUVAlarmClearLevel; 
//	        uint16_t            GLUtiLossTransientCounter;   //20171227 begin: down global ram for improve-cpu num1

        float               ActivePowerFiltered;
        float               ReactivePowerFiltered;
        stThreePhase        MasterRMSData;
		float               PeakVoltage;
//	        float               PeakVoltageLL;	//20171227 begin: down global ram for improve-cpu num2
      
        stThreePhase        ee_LoadShareVoltageCal;
//	        stThreePhase        ReactiveCurrent;	//20171227 begin: down global ram for improve-cpu:3 num6
        stThreePhase        InverterVmag;
        SineReference       SineRef;


        stThreePhase        ee_DCcomponentOffset;
        float               VoltageNormFactor;
        float               CurrentNormFactor;
        float               RMSVoltageNormFactor;
        float               RMSCurrentNormFactor;
        uint16_t            InnerLoopCount_BC;
        
//	        stSecondOrderIIRFP  InverterVGains2A;  //20171227 begin: down global ram for improve-cpu:7 num13       

        stPark              InverterCurrentDQ0Data;

		INV_LEG_ON			InverterLegOn;		//inv leg on for 3:1/1:1 cali
		//20180413 add new dcff, kpwm_=Vref(360)/Vdc		
        float 				PWMVrefCorrection;	
        float 				PWMVrefCorrectionPos;	
        float 				PWMVrefCorrectionNeg;	
		//end
		float 			    VoltageRefCorrection;

    protected:
        inline void LimitDuty( float* duty )
        {
            const float gap = 0.01;  //gap from border values   1   .5+   .5-   0

            if ( (*duty) > ( 1.0f - gap ) )
            { 
                *duty = 1.0f - gap;
            }
            else if ( (*duty) < ( gap - 1.0f ) )
            {
                *duty = gap - 1.0f;
            }
        }

        inline void DeadZoneCompenste(float TempIn, float CompensatePercent, float* duty )
		{
//	        	if(TempIn > 5.0f)
//				{
//					*duty += CompensatePercent;
//				}
//				else if(TempIn < -5.0f)
//				{
//					*duty -= CompensatePercent;
//				}

			if(TempIn > 0.01f)		//1%duty
			{
				*duty += CompensatePercent;
			}
			else if(TempIn < -0.01f)
			{
				*duty -= CompensatePercent;
			}
		}

        inline void UpdateInverterAngle_ISR( void );
        inline void InverterPWMController_ISR( void );
        void InverterDCCompensation( void );
        void InverterShortDetect(void);
        void RunVoltageRMSLoop( void );
   
    protected:
        //current loop gains
        stSecondOrderIIRFP  InverterIGainsA;
        stSecondOrderIIRFP  InverterIGainsB;
        stSecondOrderIIRFP  InverterIGainsC;
        stSecondOrderIIRFP  InverterIGainsA2;
        stSecondOrderIIRFP  InverterIGainsB2;
        stSecondOrderIIRFP  InverterIGainsC2;

		stFirstOrderIIRFP	ECTInverterIGainsA;
		stFirstOrderIIRFP	ECTInverterIGainsB;
		stFirstOrderIIRFP	ECTInverterIGainsC;
        stFirstOrderIIRFP   ECTPowerGains;
        
        //current leg share loop gains
		float OnePhaseLegLoadShareGainLeg;

        //voltage loop gains
        stSecondOrderIIRFP  InverterVGainsA;
        stSecondOrderIIRFP  InverterVGainsB;
        stSecondOrderIIRFP  InverterVGainsC;
        stSecondOrderIIRFP  InverterVGainsA2;
        stSecondOrderIIRFP  InverterVGainsB2;
        stSecondOrderIIRFP  InverterVGainsC2;
        stSecondOrderIIRFP  InverterDCCompensatorA;
        stSecondOrderIIRFP  InverterDCCompensatorB;
        stSecondOrderIIRFP  InverterDCCompensatorC;

		stFirstOrderIIRFP	IcapEstimatorGainsA;
		stFirstOrderIIRFP	IcapEstimatorGainsB;
		stFirstOrderIIRFP	IcapEstimatorGainsC;

        SineReference*      SyncSource;
        float               NominalVoltage;
        float               RMSPowerNormFactor;
        float               InvPWMPeriod;
        uInverterStatus     InverterStatus;
//	        float               SoftwareCurrentLimit;	//20171227 begin: down global ram for improve-cpu num36
		//Ect varia
        float               ECTPFAngle;
        float               ECTPFAngleTemp;
		float               ECTTotalPowerSet;		
		float				ECTPowerFactor;
		float               ECTActivePowerSet;
        float               InverterECTCurrentMag;
        float               FeedForwardGain;
        float               ZeroSequenceMagnitude;		
//	        float               CurrentReferenceMagnitude;	//20171227 begin: down global ram for improve-cpu num37
        
        //Voltage and current control variables 
        stThreePhase        InverterSineRef;
        CombinedVector      InverterVoltageFeedback;
        CombinedVector      InverterCurrentFeedback;
        CombinedVector      InverterVoltageReference;
        CombinedVector      InverterCurrentReference;
        stThreePhase        InverterDCOffset;
        stThreePhase        PWMCommand;
        
        //rms loop gains
		stFirstOrderIIRFP	InverterVRMSGainsA; 
		stFirstOrderIIRFP	InverterVRMSGainsB; 
		stFirstOrderIIRFP	InverterVRMSGainsC;
        float               VRMSSatFactor; 
        
        float               InverterVSatFactorNew;
        float               InverterISatFactorNew;		
        float               InverterVSatFactorNew2;
        // load share
//	        stSecondOrderIIRFP  LoadShareDroopTable;
		stFirstOrderIIRFP	LoadShareDroopTable;
//	        stSecondOrderIIRFP  ReactiveLoadShareDroopTable;
		stFirstOrderIIRFP	ReactiveLoadShareDroopTable;
//	        stSecondOrderIIRFP  LoadShareDCFeedForwardTable;
		stFirstOrderIIRFP  LoadShareDCFeedForwardTable;
//	        stSecondOrderIIRFP  ReactivePowerDroopTable;
		stFirstOrderIIRFP	ReactivePowerDroopTable;
        stSecondOrderIIRFP  HighDCVPhaseDroopTable;
//	        stSecondOrderIIRFP  InvCurAutoZeroFilter;
		stFirstOrderIIRFP	InvCurAutoZeroFilter;
        float               HighDCVPhaseDroopGain;
//	        float               DCFeedForwardParallelOnBoost;	//9p50k use; //20171227 begin: down global ram for improve-cpu num40

        Fir<37>             ActivePowerFilter;
        Fir<37>             ReactivePowerFilter;
        
//	        bool UPMControlsRMS;	//rsd use in 9P service; //20171227 begin: down global ram for improve-cpu
//	        float VoltageRefCorrection;
        bool MatchBypassForced;
        uint16_t StoredBypassMatchState;
        float               ReactivePowerPhaseDroop;
        
        static const uint16_t nInvCompensators = 1;

        
    private:
        stThreePhase        RMSVoltageRef;
        stThreePhase		SelectiveTripVDiff;

        // The inverter's locally defined RMS voltage.  Updated once per line
        // cycle, and scaled such that 1.0 == output nominal voltage.
        stThreePhase        NormRMSVoltageFeedback;

        float               ee_SlowSWCurrentLimit;
        uint16_t            ee_SlowSWCurrentLimitCycles;
        StateTimer          OutputShortDetectionTimer;
		
        float               FrequencyGain;
        float               PhaseError;
        float               PhaseGain;
        FilteredBit         Locked;
        stSlewRateLimits    SlewRateLimit;
        uint16_t            ParallelRMSDownSample;
        inv_slew_rate_t     SlewRate;

        uint16_t            EnableSelectiveTrip;


    protected:
//	        bool                UseThreeWireControl;
        uint16_t            DCFeedForwardEnable;
        float               InitialNormVmag;
};

extern InverterControl Inverter;

extern const stSecondOrderIIRFP InverterVoltageLoopCoefficients_20KVA_HV;
extern const stSecondOrderIIRFP InverterVoltageLoopCoefficients2_20KVA_HV;
extern const stSecondOrderIIRFP InverterCurrentLoopCoefficients_20KVA_HV;
extern const stSecondOrderIIRFP InverterCurrentLoopCoefficients2_20KVA_HV;
extern const stFirstOrderIIRFP InverterRMSLoopCoefficients_20KVA_HV;
extern const stSecondOrderIIRFP InverterDCCompensationCoefficients_20KVA_HV;
extern const stFirstOrderIIRFP LoadShareDroopCoefficients_20KVA_HV;
extern const stFirstOrderIIRFP ECTCurrentLoopCoefficients_20KVA_HV;
extern const stFirstOrderIIRFP ECTPowerLoopCoefficients_20KVA_HV;
extern const stFirstOrderIIRFP CapCurrentEstimatorCoefficients_20KVA_HV;
extern const stFirstOrderIIRFP ReactiveLoadShareDroopCoefficients_20KVA_HV;
extern const stFirstOrderIIRFP LoadShareDCFeedForwardCoefficients_20KVA_HV;
extern const stFirstOrderIIRFP ReactivePowerDroopCoefficients_20KVA_HV;
extern const stSecondOrderIIRFP HighDCVPhaseDroopCoefficients_20KVA_HV;
extern const stSecondOrderIIRFP ReactiveCurrentFilterCoefficients_20KVA_HV;

extern const stSecondOrderIIRFP InverterVoltageLoopCoefficients_40KVA_HV;
extern const stSecondOrderIIRFP InverterVoltageLoopCoefficients2_40KVA_HV;
extern const stSecondOrderIIRFP InverterCurrentLoopCoefficients_40KVA_HV;
extern const stSecondOrderIIRFP InverterCurrentLoopCoefficients2_40KVA_HV;
extern const stFirstOrderIIRFP InverterRMSLoopCoefficients_40KVA_HV;
extern const stSecondOrderIIRFP InverterDCCompensationCoefficients_40KVA_HV;
extern const stFirstOrderIIRFP LoadShareDroopCoefficients_40KVA_HV;
extern const stFirstOrderIIRFP ECTCurrentLoopCoefficients_40KVA_HV;
extern const stFirstOrderIIRFP ECTPowerLoopCoefficients_40KVA_HV;
extern const stFirstOrderIIRFP CapCurrentEstimatorCoefficients_40KVA_HV;
extern const stFirstOrderIIRFP ReactiveLoadShareDroopCoefficients_40KVA_HV;
extern const stFirstOrderIIRFP LoadShareDCFeedForwardCoefficients_40KVA_HV;
extern const stFirstOrderIIRFP ReactivePowerDroopCoefficients_40KVA_HV;
extern const stSecondOrderIIRFP HighDCVPhaseDroopCoefficients_40KVA_HV;
extern const stSecondOrderIIRFP ReactiveCurrentFilterCoefficients_40KVA_HV;

inline void ee_calc_inverter_limits( EE_ID* ee, uint16_t* data )
{
    Inverter.EEFunc_Inverter( ee, data );
}
inline void SetInv3LvlPwm(float pw, float period, const uint16_t phase);
void LoadshareThetaCompen(void);

extern float  InitDropPower;

extern float SelectiveTripDQLimit;
extern float SelectiveTripVDiffLimit;

#endif
// ******************************************************************************************************
// *            End of Inverter.h
// ******************************************************************************************************
