// ******************************************************************************************************
// *            adc.c
// ******************************************************************************************************
// ********************************************************************
// *
// * THIS information is proprietary to Eaton Corporation
// *
// ********************************************************************
// *
// *  Copyright (c) 2003 Eaton Powerware
// *    ALL RIGHTS RESERVED
// *
// ********************************************************************
// ******************************************************************************************************
// *    FILE NAME: adc.c
// *
// *    DESCRIPTION: Performs initialization of a2d and other additional a2d functions.
// *
// *    ORIGINATOR: Hans Pfitzer
// *
// *    DATE: 3/14/2003
// *
// *    HISTORY: See Visual Source Safe history.
// ******************************************************************************************************

// ******************************************************************************************************
// * INCLUDE FILES
// ******************************************************************************************************
#include "DSP28x_Project.h"     // Device Headerfile and Examples Include File
#include "F28335Port.h"
#include "MCUState.h"
#include "adc.h"
#include "Algos.h"
#include "Meters.h"
#include "BypassInterface.h"
#include "InverterControl.h"
#include "RectifierStateControl.h"
#include "Alarms.h"
#include "DQPhaseLockLoop.h"
#include "Alarms_AC.h"
#include "InvSync.h"
#include "BatteryStateControl.h"
#include "Thermal.h"             
#include "ParallelCan.h"
#include "ACPowerMeter.h"
#include "VirtualNeutralMeter.h"
#include "IOexpansion.h"      
#include "SystemTrap.h"       
#include "ACMeter.h"
#include "ExtSignalPLL.h"
#include "Coefficients.h"
#include "Eeprom_Map.h"

extern "C"
{
    void ProcessA2D_HWI(void);
}
// ********************************************************************
//      Macro
// ********************************************************************
#define 	cFreq4_333kHz		4333	//26k/6
#define 	cFreq2_167kHz		2167	//26k/6/2
// ********************************************************************
//      Global data
// ********************************************************************
extern void I2c_StateCheck(void);

// ********************************************************************
// * FILE VARIABLES
// ********************************************************************
static uint16_t ExecutionState = 0;
bool PreventWatchdogKick = 0;
extern float BatteryCurrentPos_Sum_SlowFilter;	//legA + legB
extern float BatteryCurrentNeg_Sum_SlowFilter;	//legA + legB

// ********************************************************************
// * LOCAL FUNCTION PROTOTYPES
// ********************************************************************
void Even2_5kHzFunction( void );
void Odd2_5kHzFunction( void );
void Function1_25kHz_0( void );
void Function1_25kHz_1( void );
void Function1_25kHz_2( void );
void Function1_25kHz_3( void );
void LNtoLL( const stThreePhase* restrict ln, stThreePhase* restrict ll );

// ********************************************************************
// * EXTERNAL FUNCTION PROTOTYPES
// ********************************************************************

// ********************************************************************************************************
// *
// * Function: void ProcessA2D_Intr(void)
// *
// * Purpose: Interrupt generated by the Adc to process (MS, ZC, Power) the A2D's and run the state machine
// *
// * Parms Passed   :   Nothing
// * Returns        :   Nothing
// *
// * Description: Interrupt generated by the Adc
// *              Run in 231us interval
// *
// ********************************************************************************************************
#pragma CODE_SECTION( "ramfuncs" )
void ProcessA2D_HWI(void)			//4.33kHz, 231us
{
    const uint16_t ZeroCrossTimeout = 109;          // 109 * 231us = ~25.1ms or 39.8Hz
    
    static float lastInverterAngle = 0;
    static float lastUtilityAngle = 0;
    static float lastBypassAngle = 0;
    
    // these 2 require timeouts so that the zero cross function is still called if
    // the source is not present
    static uint16_t UtilityZeroCrossTimeout = ZeroCrossTimeout;
    static uint16_t BypassZeroCrossTimeout = ZeroCrossTimeout;
    static uint16_t InverterZeroCrossTimeout = ZeroCrossTimeout;

    
    ReadDSPInputs();                        // Read GPIO
    ProcessSlowAdc();                       // process slow adc channels
    if ( MCUStateMachine.GetStatus().bit.AutoZeroHallSensors )
    {
        CurrentSensorAutoZero();
    }

    // Note: BypassSensorAutoZero() isn't working properly right now, and it is never run.
    // It never settles on a stable zero. The default value of 2048 works well enough for now.
    //if ( MCUStateMachine.GetStatus().bit.AutoZeroBypassSensors )
    //{
    //    BypassSensorAutoZero();
    //}

    if ( BatteryConverter.GetBatteryStateStatusPtr()->bit.AutoZeroBatteryCurrentSensors )
    {
        BatteryCurrentAutoZero();
    } 
    
    // 3 phase RMS voltage sum of squares
    if ( MCUStateMachine.GetADCReadyFlag() )
    {
        UtilityVoltageRMS.ProcessRawAC();
        InverterVoltageRMS.ProcessRawAC();
        BypassVoltageRMS.ProcessRawAC();
        OutputVoltageRMS.ProcessRawAC();
        BypassVoltage2RMS.ProcessRawAC();
        
        // 3 phase RMS current sum of squares
        UtilityCurrentRMS.ProcessRawAC();
        InverterCurrentRMS.ProcessRawAC();
        BypassCurrentRMS.ProcessRawAC();
        ChassisVoltageRMS.ProcessRawAC();		
        ProcessOutReactiveCurrent();
    }
    
    // DC voltages, not sure about the battery
    if ( MCUStateMachine.GetADCReadyFlag() )
    {
        ProcessDC( RawAdcDataPtr->st.RailVoltagePositive, ( stDC_Meter* )&DCLinkVoltagePositive );
        ProcessDC( RawAdcDataPtr->st.RailVoltageNegative, ( stDC_Meter* )&DCLinkVoltageNegative );
        ProcessDC( RawAdcDataPtr->st.BatteryVoltage,  ( stDC_Meter* )&BatteryVoltage );
        ProcessDC( RawAdcDataPtr->st.BatteryVoltagePos,  ( stDC_Meter* )&BatteryVoltagePos );		
        ProcessDC( RawAdcDataPtr->st.BatteryVoltageChgPos,  ( stDC_Meter* )&BatteryVoltageChgPos );
        ProcessDC( RawAdcDataPtr->st.BatteryVoltageChgNeg,  ( stDC_Meter* )&BatteryVoltageChgNeg );
        ProcessDC( (RawAdcDataPtr->st.BatteryVoltageChgPos - RawAdcDataPtr->st.BatteryVoltageChgNeg), ( stDC_Meter* )&BatteryVoltageBU );
        ProcessDC( RawAdcDataPtr->st.InverterDCPhaseA,  ( stDC_Meter* )&InverterDCphA );
        ProcessDC( RawAdcDataPtr->st.InverterDCPhaseB,  ( stDC_Meter* )&InverterDCphB );
        ProcessDC( RawAdcDataPtr->st.InverterDCPhaseC,  ( stDC_Meter* )&InverterDCphC );    

        ProcessDC( RawAdcDataPtr->st.BatteryCurrentPositive, ( stDC_Meter* )&BatteryCurrentPos );	//LegA
        ProcessDC( RawAdcDataPtr->st.BatteryCurrentNegative, ( stDC_Meter* )&BatteryCurrentNeg );
		if(Rectifier.ReuseRectSTPWMEnable)
		{
	        ProcessDC( (-RawAdcDataPtr->st.InputCurrent.phB), ( stDC_Meter* )&BatteryCurrentPos_LegB );
	        ProcessDC( (RawAdcDataPtr->st.InputCurrent.phC), ( stDC_Meter* )&BatteryCurrentNeg_LegB );
		}
		else
		{
	        ProcessDC( 0.0f, ( stDC_Meter* )&BatteryCurrentPos_LegB );
	        ProcessDC( 0.0f, ( stDC_Meter* )&BatteryCurrentNeg_LegB );
//				BatteryCurrentPos_LegB.FastFiltered = 0.0f;
//				BatteryCurrentPos_LegB.SlowFiltered = 0.0f;
//				BatteryCurrentNeg_LegB.FastFiltered = 0.0f;
//				BatteryCurrentNeg_LegB.SlowFiltered = 0.0f;
		}
		BatteryCurrentPos_Sum_SlowFilter = BatteryCurrentPos.SlowFiltered + BatteryCurrentPos_LegB.SlowFiltered;
		BatteryCurrentNeg_Sum_SlowFilter = BatteryCurrentNeg.SlowFiltered + BatteryCurrentNeg_LegB.SlowFiltered;
		BatteryVoltageNeg_SlowFiltered =  -(BatteryVoltage.SlowFiltered - BatteryVoltagePos.SlowFiltered);
	
        ProcessDC( RawAdcDataPtr->st.InputVoltageNeutral,     ( stDC_Meter* )&InputNeutral );
            

    }
    
    MCUStateMachine.Run();                           // Execute the state machine, 5.1 kHz sampling.
    BatteryConverter.RunBatteryState();
    BatteryConverter.RunBoost();
//	    BatteryConverter.RunBoostPowerMode();	//Hobbit rec single direction, can not run boostpower
    
    // rectifier outer link control
    Rectifier.OuterVoltageControl();
    
    // check for inverter zero crossing
    float inverterAngle = Inverter.GetAngle();
    --InverterZeroCrossTimeout;
    if ( ( ( lastInverterAngle < 0.0 ) && ( inverterAngle >= 0.0 ) ) ||
         ( 0 == InverterZeroCrossTimeout ) )
    {
        MCUStateMachine.ZeroCross.Trigger( INVERTER_ZERO_CROSSING );
        SWI_post( &SWI_InverterZeroCross );
        InverterZeroCrossTimeout = ZeroCrossTimeout;

    }
    lastInverterAngle = inverterAngle;

    // check for utility zero crossing
    float utilityAngle = Rectifier.UtilityPLL.SineRef.Angle;
    --UtilityZeroCrossTimeout;
    if ( ( ( lastUtilityAngle < 0.0 ) && ( utilityAngle >= 0.0 ) ) ||
         ( 0 == UtilityZeroCrossTimeout ) )
    {
        MCUStateMachine.ZeroCross.Trigger( UTILITY_ZERO_CROSSING );
        SWI_post( &SWI_UtilityZeroCross );
        UtilityZeroCrossTimeout = ZeroCrossTimeout;
    }
    lastUtilityAngle = utilityAngle; 
    
    // check for bypass zero crossing
    float bypassAngle = BypassPLL.SineRef.Angle;
    --BypassZeroCrossTimeout;
    if ( ( ( lastBypassAngle < 0.0 ) && ( bypassAngle >= 0.0 ) ) ||
         ( 0 == BypassZeroCrossTimeout ) )
    {
        MCUStateMachine.ZeroCross.Trigger( BYPASS_ZERO_CROSSING );
        SWI_post( &SWI_BypassZeroCross );
        BypassZeroCrossTimeout = ZeroCrossTimeout;
    }
    lastBypassAngle = bypassAngle;       
    
    // sub 4.3 kHz functions
    switch ( ExecutionState & 0x3 )
    {
        case 0:
            Even2_5kHzFunction();
            Function1_25kHz_0();
            break;

        case 1:
            Odd2_5kHzFunction();
            Function1_25kHz_1();
            break;

        case 2:
            Even2_5kHzFunction();
            Function1_25kHz_2();
            break;

        case 3:
            Odd2_5kHzFunction();
            Function1_25kHz_3();
            break;
        
        //Add for PC lint rule: switch statement should have default
        default:
            break;
    }

    ExecutionState++;

    // Process Thermal
    ProcessThermal();
    
    CheckInstantVoltage();
    // Acknowledge interrupt and return
    PieCtrlRegs.PIEACK.all = PIEACK_GROUP2;     // Acknowledge interrupt to PIE
    
}

// ********************************************************************************************************
// *
// * Function: Even2_5kHzFunction
// *
// * Purpose:  Interrupts function run every other A2D interrupt
// *
// * Parms Passed   :   Nothing
// * Returns        :   Nothing
// *
// * Description: Execution state 0 and 2
// *
// ********************************************************************************************************
#pragma CODE_SECTION( "ramfuncs" )
void Even2_5kHzFunction (void)
{
   float ecoCapacitance = capacitance * NumOfUPMs;
    const float inv_dt = cFreq2_167kHz;//2551.0f;
    
    // klv: Is it a good idea to be kicking the dog in an interrupt? Seems to me should be in a low
    // priority task
    if(!PreventWatchdogKick)
    {
        KickWatchdog();
    }

    stThreePhase deltaVdt = {
        (RawAdcDataPtr->st.OutputVoltageRaw.phA - LoadPower.LastVoltage.phA) * inv_dt,
        (RawAdcDataPtr->st.OutputVoltageRaw.phB - LoadPower.LastVoltage.phB) * inv_dt,
        (RawAdcDataPtr->st.OutputVoltageRaw.phC - LoadPower.LastVoltage.phC) * inv_dt,
    };  
      
    // Copy current power when transfer happens. Power meters are slow otherwise.
    switch ( MCUStateMachine.GetState() )
    {
        // Puck/20120731, add SHUTDOWN_STATE and STANDBY_STATE for debug when UPS on TestMode.
        case SHUTDOWN_STATE:
        case STANDBY_STATE:
        case ONLINE_STATE:
        case EASY_CAPACITY_TEST_STATE: {
            // Compensate for inverter cap current in the power calcs

            // Estimate output current
            OutputCurrent.phA = RawAdcDataPtr->st.InverterCurrent.phA;
            OutputCurrent.phB = RawAdcDataPtr->st.InverterCurrent.phB;
            OutputCurrent.phC = RawAdcDataPtr->st.InverterCurrent.phC;
        
            OutputCurrent.phA -= deltaVdt.phA * capacitance;
            OutputCurrent.phB -= deltaVdt.phB * capacitance;
            OutputCurrent.phC -= deltaVdt.phC * capacitance;

            OutputCurrentRMS.ProcessRawAC();    
            LoadPower.ProcessPower( &RawAdcDataPtr->st.OutputVoltageRaw, &OutputCurrent );
            break;
        }

        case BYPASS_STATE:
            LoadPower.ProcessPower( &RawAdcDataPtr->st.OutputVoltageRaw, &RawAdcDataPtr->st.BypassCurrent );
            break;
                    
        case BYPASS_STANDBY_STATE:
            LoadPower.ProcessPower( &RawAdcDataPtr->st.OutputVoltageRaw, &RawAdcDataPtr->st.BypassCurrent );
            break;
            
        case ESS_MODE_STATE:
            // Estimate output current, and compensate for all inverter's cap current
            OutputCurrent.phA = RawAdcDataPtr->st.BypassCurrent.phA;
            OutputCurrent.phB = RawAdcDataPtr->st.BypassCurrent.phB;
            OutputCurrent.phC = RawAdcDataPtr->st.BypassCurrent.phC;
        
            OutputCurrent.phA -= deltaVdt.phA * ecoCapacitance;
            OutputCurrent.phB -= deltaVdt.phB * ecoCapacitance;
            OutputCurrent.phC -= deltaVdt.phC * ecoCapacitance;

            OutputCurrentRMS.ProcessRawAC();
            LoadPower.ProcessPower( &RawAdcDataPtr->st.OutputVoltageRaw, &OutputCurrent );
            break;

        default:
            break;
    }

    CheckAlarmsFast();
    
    InverterPower.ProcessPower( &RawAdcDataPtr->st.InverterVoltage, &RawAdcDataPtr->st.InverterCurrent );
    RectifierPower.ProcessPower( &RawAdcDataPtr->st.InputVoltage, &RawAdcDataPtr->st.InputCurrent );
    BypassPower.ProcessPower( &RawAdcDataPtr->st.BypassVoltage, &RawAdcDataPtr->st.BypassCurrent );

    ParallelSystem392us_Function();
}

// ********************************************************************************************************
// *
// * Function: Odd2_5kHzFunction
// *
// * Purpose:  Interrupts function run every other A2D interrupt
// *
// * Parms Passed   :   Nothing
// * Returns        :   Nothing
// *
// * Description: Execution state 1 and 3
// *
// ********************************************************************************************************
#pragma CODE_SECTION( "ramfuncs" )
void Odd2_5kHzFunction (void)
{
    if( !FrequencyConverterMode )
    {
        BypassState().RunStateMachine();
    }
    Rectifier.RunRectiferState();
    
    BypassPLL.RunPLLFast();
    OutputPLL.RunPLLFast();
   // ExtSyncSource.RunPLLFast();
    ExtSignalSync.RunPLLFast();
    // rectifier takes care of itself    
}

// ********************************************************************************************************
// *
// * Function: Function1_25kHz_0
// *
// * Purpose:  Interrupt function run every fourth A2D interrupt
// *
// * Parms Passed   :   Nothing
// * Returns        :   Nothing
// *
// * Description: Execution state 0
// *
// ********************************************************************************************************
#pragma CODE_SECTION( "ramfuncs" )
void Function1_25kHz_0 (void)
{
    Inverter.RunPLLFast();
    CheckFastACAlarms();
}

// ********************************************************************************************************
// *
// * Function: Function1_25kHz_1
// *
// * Purpose:  Interrupts function run every fourth A2D interrupt
// *
// * Parms Passed   :   Nothing
// * Returns        :   Nothing
// *
// * Description: Execution state 1
// *
// ********************************************************************************************************
#pragma CODE_SECTION( "ramfuncs" )
void Function1_25kHz_1 (void)
{
//	    VirtualInputNeutralA.ProcessRawAC();
//	    VirtualInputNeutralB.ProcessRawAC();
//	    VirtualInputNeutralC.ProcessRawAC();
}

// ********************************************************************************************************
// *
// * Function: Function1_25kHz_2
// *
// * Purpose:  Interrupts function run every fourth A2D interrupt
// *
// * Parms Passed   :   Nothing
// * Returns        :   Nothing
// *
// * Description: Execution state 2
// *
// ********************************************************************************************************
#pragma CODE_SECTION( "ramfuncs" )
void Function1_25kHz_2 (void)
{
//	    DirectInputNeutral.ProcessRawDC();
//	    DirectInputVoltSum.ProcessRawDC();
}

// ********************************************************************************************************
// *
// * Function: Function1_25kHz_3
// *
// * Purpose:  Interrupts function run every fourth A2D interrupt
// *
// * Parms Passed   :   Nothing
// * Returns        :   Nothing
// *
// * Description: Execution state 3
// *              Runs inverter volt-seconds FIR
// *
// ********************************************************************************************************
#pragma CODE_SECTION( "ramfuncs" )
void Function1_25kHz_3 (void)
{
    I2c_StateCheck();
    SyncState();
}

// ********************************************************************************************************
// *
// * Function: LNtoLL
// *
// * Purpose:  calculates ll voltages from ln
// *
// * Parms Passed   :   pointer to ln voltages to convert
// *                    pointer to ll voltages for result
// * Returns        :   Nothing
// *
// * Description:
// *
// ********************************************************************************************************
#pragma CODE_SECTION( "ramfuncs" )
void LNtoLL( const stThreePhase* restrict ln, stThreePhase* restrict ll )
{
    ll->phA = ln->phA - ln->phB;
    ll->phB = ln->phB - ln->phC;
    ll->phC = ln->phC - ln->phA;
}
// ********************************************************************************************************
//      End of ProcessAdc.c
// ********************************************************************************************************

