// ******************************************************************************************************
// *            ProcessAC.c
// ******************************************************************************************************
// ******************************************************************************************************
// *
// *    THIS INFORMATION IS PROPRIETARY TO Eaton Corporation
// *
// ******************************************************************************************************
// *
// *    Copyright (c) 2003 Eaton
// *    ALL RIGHTS RESERVED
// *
// ******************************************************************************************************
// ******************************************************************************************************
// *    FILE NAME: ProcessAC.c
// *
// *    DESCRIPTION:
// *
// *    ORIGINATOR: Jason Anderson
// *                Mike Westerfield
// *
// *
// *    DATE: 5/8/2003
// *
// *    HISTORY: See Visual Source Safe history.
// ******************************************************************************************************

// *********************************************************************************************************
// *        INCLUDE FILES
// *********************************************************************************************************
#include "DSP28x_Project.h"     // Device Headerfile and Examples Include File
#include "Constants.h"
#include "Adc.h"
#include "Alarms_AC.h"
#include "Meters.h"
#include "NB_Config.h"
#include "NB_Funcs.h"
#include "MCUState.h"
#include "DQPhaseLockLoop.h"
#include "Eeprom_map.h"
#include "InverterControl.h"
#include "Abm.h"
#include "BTR.h"
#include "ACMeter.h"
#include "ACPowerMeter.h"
#include "BypassInterface.h"
#include <cmath>
#include "ProcessAdc.h"

using namespace std;

const stAC_Power    ZeroPower = {0, 0, 0, 0};
const stThreePhase  Zero3P    = {0, 0, 0};
extern uint16_t NumOfModule;

// simple first order filter for now, 5ms Tc@Ts = 192us
const stSecondOrderIIRFP IIR5msGains    = { 0.039200314, 0, 0, -0.960799686, 0, 0, 0 };
// * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
// * Generated by MATLAB(R) 7.8 and the Signal Processing Toolbox 6.11.
// * Generated on: 30-Mar-2010 18:13:06
// 
// * Discrete-Time IIR Filter (real)
// * -------------------------------
// * Filter Structure    : Direct-Form II, Second-Order Sections
// * Number of Sections  : 1
// * Stable              : Yes
// * Linear Phase        : No
// * Params:
// * LowPass- Elliptic
// * Fs = 5102Hz
// * Fpass = 15Hz
// * Fstop = 55Hz
// * Apass = 1
// * Astop = 25
// * Specifically designed to filter out 60Hz ripple, of which there is alot since we got real skinny real caps
const stSecondOrderIIRFP IIRDCSlowGains = { 0.06257314, -1.993885114290207, 0.99999999999999967, -1.980209351022385,  0.9805919782185083, 0, 0 };

// ********************************************************************************************************
// *        Global Data
// ********************************************************************************************************
// DC voltages
volatile stDC_Meter DCLinkVoltagePositive   = { 0, 0, IIR5msGains, IIRDCSlowGains };
volatile stDC_Meter DCLinkVoltageNegative   = { 0, 0, IIR5msGains, IIRDCSlowGains };
volatile stDC_Meter BatteryVoltage          = { 0, 0, IIR5msGains, IIRDCSlowGains };
volatile stDC_Meter BatteryVoltagePos       = { 0, 0, IIR5msGains, IIRDCSlowGains };
volatile stDC_Meter BatteryVoltageChgPos    = { 0, 0, IIR5msGains, IIRDCSlowGains };
volatile stDC_Meter BatteryVoltageChgNeg    = { 0, 0, IIR5msGains, IIRDCSlowGains };
volatile stDC_Meter BatteryVoltageBU        = { 0, 0, IIR5msGains, IIRDCSlowGains };
volatile stDC_Meter BatteryCurrentNeg       = { 0, 0, IIR5msGains, IIRDCSlowGains };
volatile stDC_Meter BatteryCurrentPos       = { 0, 0, IIR5msGains, IIRDCSlowGains }; 
volatile stDC_Meter InverterDCphA           = { 0, 0, IIR5msGains, IIRDCSlowGains };
volatile stDC_Meter InverterDCphB           = { 0, 0, IIR5msGains, IIRDCSlowGains };
volatile stDC_Meter InverterDCphC           = { 0, 0, IIR5msGains, IIRDCSlowGains };
volatile stDC_Meter BatteryCurrentPos_LegB      = { 0, 0, IIR5msGains, IIRDCSlowGains };	//LegB_Pos: RecS
volatile stDC_Meter BatteryCurrentNeg_LegB      = { 0, 0, IIR5msGains, IIRDCSlowGains };	//LegB_Neg: RecT
float BatteryCurrentPos_Sum_SlowFilter = 0.0f;	//legA + legB
float BatteryCurrentNeg_Sum_SlowFilter = 0.0f;	//legA + legB
float BatteryVoltageNeg_SlowFiltered = 0.0f;       
volatile stDC_Meter InputNeutral            = { 0, 0, IIR5msGains, IIRDCSlowGains };


// DC currents ??
//volatile stDC_Meter BatteryCurrent = { 0, IIR5msGains, IIRDCSlowGains };

stScreenMeters ScreenMeters;
stThreePhase AvgAmpsOutVar = {0, 0, 0};
stThreePhase indCurrentLimit = {-16.0f, -16.0f, -16.0f};
stThreePhase CapCurrentAdj = {24.0f, 24.0f, 24.0f};
float PFfiltergain = 8.0f;
// ********************************************************************************************************
// * LOCAL FUNCTION PROTOTYPES
// ********************************************************************************************************
static void CalculatePercentLoad( void );

// ********************************************************************************************************
// *
// * Function: ProcessDC( volatile float dcRaw, stDC_Meter* ptrDc );
// *
// * Purpose: Filters some dc measurements
// *
// * Parms Passed   :   rawdc, pointer to stDC_Meter
// * Returns        :   Nothing
// *
// * Description:  runs 2 filters, fast and slow
// * 
// * INTERRUPT FUNCTION
// ********************************************************************************************************
#pragma CODE_SECTION( "ramfuncs" )
void ProcessDC( volatile const float dcRaw, stDC_Meter* ptrDc )
{
    // NOTE: It is the caller's responsibility to make sure this should be run!
    ptrDc->FastFiltered = SecondOrderIIRFP( (float)dcRaw, &ptrDc->Filter5ms );
    ptrDc->SlowFiltered = SecondOrderIIRFP( (float)dcRaw, &ptrDc->Filter250ms );
}

// ********************************************************************************************************
// *
// * Function: ProcessACScreenMeters( void );
// *
// * Purpose: updates the filtered RMS data
// *
// * Parms Passed   :   nothing
// * Returns        :   Nothing
// *
// * Description:
// * 
// * TASK FUNCTION 500ms
// ********************************************************************************************************
void ProcessACScreenMeters( void )
{
    const float cosine_120 = -0.5f;
	//  input voltage
    ScreenMeters.InputVoltageRMS.phA       = ( UtilityVoltageRMS.FilteredRMS.phA > 50.0f )? UtilityVoltageRMS.FilteredRMS.phA : 0.0;
    ScreenMeters.InputVoltageRMS.phB       = ( UtilityVoltageRMS.FilteredRMS.phB > 50.0f )? UtilityVoltageRMS.FilteredRMS.phB : 0.0;
    ScreenMeters.InputVoltageRMS.phC       = ( UtilityVoltageRMS.FilteredRMS.phC > 50.0f )? UtilityVoltageRMS.FilteredRMS.phC : 0.0;

    if( UtilityVoltageRMS.FilteredRMS.phA > 50.0f )
    {
        ScreenMeters.InputVoltageLL_RMS.phA = 
            sqrt( UtilityVoltageRMS.FilteredRMS.phA * UtilityVoltageRMS.FilteredRMS.phA +
                  UtilityVoltageRMS.FilteredRMS.phB * UtilityVoltageRMS.FilteredRMS.phB -
                  2 * UtilityVoltageRMS.FilteredRMS.phA * UtilityVoltageRMS.FilteredRMS.phB * cosine_120 );
    }
    else
    {
        ScreenMeters.InputVoltageLL_RMS.phA = 0.0f;
    }
    if( UtilityVoltageRMS.FilteredRMS.phB > 50.0f )
    {
        ScreenMeters.InputVoltageLL_RMS.phB = 
            sqrt( UtilityVoltageRMS.FilteredRMS.phB * UtilityVoltageRMS.FilteredRMS.phB +
                  UtilityVoltageRMS.FilteredRMS.phC * UtilityVoltageRMS.FilteredRMS.phC -
                  2 * UtilityVoltageRMS.FilteredRMS.phB * UtilityVoltageRMS.FilteredRMS.phC * cosine_120 );
    }
    else
    {
        ScreenMeters.InputVoltageLL_RMS.phB = 0.0f;
    }
    if( UtilityVoltageRMS.FilteredRMS.phC > 50.0f )
    {
        ScreenMeters.InputVoltageLL_RMS.phC =
            sqrt( UtilityVoltageRMS.FilteredRMS.phC * UtilityVoltageRMS.FilteredRMS.phC +
                  UtilityVoltageRMS.FilteredRMS.phA * UtilityVoltageRMS.FilteredRMS.phA -
                  2 * UtilityVoltageRMS.FilteredRMS.phC * UtilityVoltageRMS.FilteredRMS.phA * cosine_120 );
    }
    else
    {
        ScreenMeters.InputVoltageLL_RMS.phC = 0.0f;
    }
    
    // inverter voltage
    ScreenMeters.InverterVoltageRMS     = ( NB_GetNodebit( UPM_NB_INVERTER_ON ) ) ? InverterVoltageRMS.FilteredRMS : Zero3P;
    
    if( NB_GetNodebit( UPM_NB_INVERTER_ON ) )
    {
        ScreenMeters.InverterVoltageLL_RMS.phA = 
            sqrt( InverterVoltageRMS.FilteredRMS.phA * InverterVoltageRMS.FilteredRMS.phA +
                  InverterVoltageRMS.FilteredRMS.phB * InverterVoltageRMS.FilteredRMS.phB -
                  2 * InverterVoltageRMS.FilteredRMS.phA * InverterVoltageRMS.FilteredRMS.phB * cosine_120 );
        ScreenMeters.InverterVoltageLL_RMS.phB = 
            sqrt( InverterVoltageRMS.FilteredRMS.phB * InverterVoltageRMS.FilteredRMS.phB +
                  InverterVoltageRMS.FilteredRMS.phC * InverterVoltageRMS.FilteredRMS.phC -
                  2 * InverterVoltageRMS.FilteredRMS.phB * InverterVoltageRMS.FilteredRMS.phC * cosine_120 );
        ScreenMeters.InverterVoltageLL_RMS.phC =
            sqrt( InverterVoltageRMS.FilteredRMS.phC * InverterVoltageRMS.FilteredRMS.phC +
                  InverterVoltageRMS.FilteredRMS.phA * InverterVoltageRMS.FilteredRMS.phA -
                  2 * InverterVoltageRMS.FilteredRMS.phC * InverterVoltageRMS.FilteredRMS.phA * cosine_120 );
    }
    else
    {
        ScreenMeters.InverterVoltageLL_RMS = Zero3P;
    }

    // output voltage
    ScreenMeters.OutputVoltageRMS       = MCUStateMachine.SupportingLoad() ? OutputVoltageRMS.FilteredRMS : Zero3P;

    if ( OutputVoltageRMS.FilteredRMS.phA > 50.0f )
    {
        ScreenMeters.OutputVoltageLL_RMS.phA = 
            sqrt( OutputVoltageRMS.FilteredRMS.phA * OutputVoltageRMS.FilteredRMS.phA +
                  OutputVoltageRMS.FilteredRMS.phB * OutputVoltageRMS.FilteredRMS.phB -
                  2 * OutputVoltageRMS.FilteredRMS.phA * OutputVoltageRMS.FilteredRMS.phB * cosine_120 );
    }
    else
    {
        ScreenMeters.OutputVoltageLL_RMS.phA = 0.0f;
    }
    if ( OutputVoltageRMS.FilteredRMS.phB > 50.0f )
    {
        ScreenMeters.OutputVoltageLL_RMS.phB = 
            sqrt( OutputVoltageRMS.FilteredRMS.phB * OutputVoltageRMS.FilteredRMS.phB +
                  OutputVoltageRMS.FilteredRMS.phC * OutputVoltageRMS.FilteredRMS.phC -
                  2 * OutputVoltageRMS.FilteredRMS.phB * OutputVoltageRMS.FilteredRMS.phC * cosine_120 );
    }
    else
    {
        ScreenMeters.OutputVoltageLL_RMS.phB = 0.0f;
    }
    if ( OutputVoltageRMS.FilteredRMS.phC > 50.0f )
    {
        ScreenMeters.OutputVoltageLL_RMS.phC =
            sqrt( OutputVoltageRMS.FilteredRMS.phC * OutputVoltageRMS.FilteredRMS.phC +
                  OutputVoltageRMS.FilteredRMS.phA * OutputVoltageRMS.FilteredRMS.phA -
                  2 * OutputVoltageRMS.FilteredRMS.phC * OutputVoltageRMS.FilteredRMS.phA * cosine_120 );
    }
    else
    {
        ScreenMeters.OutputVoltageLL_RMS.phC = 0.0f;
    }

    // bypass voltage
    ScreenMeters.BypassVoltageRMS.phA       = ( BypassVoltageRMS.FilteredRMS.phA > 50.0f )? BypassVoltageRMS.FilteredRMS.phA : 0.0;
    ScreenMeters.BypassVoltageRMS.phB       = ( BypassVoltageRMS.FilteredRMS.phB > 50.0f )? BypassVoltageRMS.FilteredRMS.phB : 0.0;
    ScreenMeters.BypassVoltageRMS.phC       = ( BypassVoltageRMS.FilteredRMS.phC > 50.0f )? BypassVoltageRMS.FilteredRMS.phC : 0.0;

    if( BypassVoltageRMS.FilteredRMS.phA > 50.0f )
    {
        ScreenMeters.BypassVoltageLL_RMS.phA = 
            sqrt( BypassVoltageRMS.FilteredRMS.phA * BypassVoltageRMS.FilteredRMS.phA +
                  BypassVoltageRMS.FilteredRMS.phB * BypassVoltageRMS.FilteredRMS.phB -
                  2 * BypassVoltageRMS.FilteredRMS.phA * BypassVoltageRMS.FilteredRMS.phB * cosine_120 );
    }
    else
    {
        ScreenMeters.BypassVoltageLL_RMS.phA = 0.0f;
    }
    if( BypassVoltageRMS.FilteredRMS.phB > 50.0f )
    {
        ScreenMeters.BypassVoltageLL_RMS.phB = 
            sqrt( BypassVoltageRMS.FilteredRMS.phB * BypassVoltageRMS.FilteredRMS.phB +
                  BypassVoltageRMS.FilteredRMS.phC * BypassVoltageRMS.FilteredRMS.phC -
                  2 * BypassVoltageRMS.FilteredRMS.phB * BypassVoltageRMS.FilteredRMS.phC * cosine_120 );
    }
    else
    {
        ScreenMeters.BypassVoltageLL_RMS.phB = 0.0f;
    }
    if( BypassVoltageRMS.FilteredRMS.phC > 50.0f )
    {
        ScreenMeters.BypassVoltageLL_RMS.phC =
            sqrt( BypassVoltageRMS.FilteredRMS.phC * BypassVoltageRMS.FilteredRMS.phC +
                  BypassVoltageRMS.FilteredRMS.phA * BypassVoltageRMS.FilteredRMS.phA -
                  2 * BypassVoltageRMS.FilteredRMS.phC * BypassVoltageRMS.FilteredRMS.phA * cosine_120 );
    }
    else
    {
        ScreenMeters.BypassVoltageLL_RMS.phC = 0.0f;
    }

    // bypass 2, doesn't go to the display so it's not masked
    ScreenMeters.BypassVoltage2RMS = BypassVoltage2RMS.FilteredRMS;

    // RMS currents
    if (NB_GetNodebit(UPM_NB_RECTIFIER_SWITCHGEAR_OPEN))
    {
        // Force to zero.  Somewhat heavy-handed way of ensuring that the
        // neutral balancing current in rectifier phase A is not seen on
        // the screen when on battery and supplying an unbalanced load.
        // not heavy handed, but normal
        ScreenMeters.InputCurrentRMS = Zero3P;
    }
    else
    {
        ScreenMeters.InputCurrentRMS = UtilityCurrentRMS.FilteredRMS;
    }

    ScreenMeters.InverterCurrentRMS = ( NB_GetNodebit( UPM_NB_INVERTER_ON ) ) ? InverterCurrentRMS.FilteredRMS : Zero3P;
    ScreenMeters.BypassCurrentRMS = ( BYPASS_FIRE_STATE == BypassState().GetMonitoredBypassState() ) ? BypassCurrentRMS.FilteredRMS : Zero3P;
    
    RectifierPower.ActivePowerFiltered.UpdateSum();
    // input/output power
    if ( Rectifier.GetStatus().bit.RectifierOnNormal )
    {
        ScreenMeters.InputPower = RectifierPower.ActivePowerFiltered;
//         ScreenMeters.InputPower.phB = RectifierPower.ActivePowerFiltered.phB;
//         ScreenMeters.InputPower.phC = RectifierPower.ActivePowerFiltered.phC;
//         ScreenMeters.InputPower.UpdateSum();
    }
    else
    {
        ScreenMeters.InputPower = ZeroPower;
    }

    CheckSTSWshort();

    LoadPower.ActivePowerFiltered.UpdateSum();
    LoadPower.TotalPowerFiltered.UpdateSum();
    
    CalculatePercentLoad();         // check before setting output power
    
    if ( ( ScreenMeters.PercentLoadWatts.phA < float( MinLoadForMeterDisplay ) ) &&
         ( ScreenMeters.PercentLoadWatts.phB < float( MinLoadForMeterDisplay ) ) &&
         ( ScreenMeters.PercentLoadWatts.phC < float( MinLoadForMeterDisplay ) ) )         // power will be masked out in CalculatePercentLoad() if load off or less than 5%
    {
        ScreenMeters.OutputCurrentRMS = Zero3P;
        ScreenMeters.OutputPower = ZeroPower;
        ScreenMeters.OutputVoltAmperes = ZeroPower;
        ScreenMeters.OutputPowerFactor = 1.0f;              // 0 / 0 but have to put something
        ScreenMeters.BypassCurrentRMS = Zero3P;
    }
    else
    {
        // phA
        if ( ScreenMeters.PercentLoadWatts.phA < float( MinLoadForMeterDisplay ) )         // power will be masked out in CalculatePercentLoad() if load off or less than 5%
        {
            ScreenMeters.OutputCurrentRMS.phA = 0.0;
            ScreenMeters.OutputPower.phA = 0.0;
            ScreenMeters.OutputVoltAmperes.phA = 0.0;
            ScreenMeters.BypassCurrentRMS.phA = 0.0;
        }
        else
        {
            ScreenMeters.OutputPower.phA = ( LoadPower.ActivePowerFiltered.phA > 0 ) ? LoadPower.ActivePowerFiltered.phA : 0;
            ScreenMeters.OutputVoltAmperes.phA = ( LoadPower.TotalPowerFiltered.phA > LoadPower.ActivePowerFiltered.phA ) ? LoadPower.TotalPowerFiltered.phA : LoadPower.ActivePowerFiltered.phA;      
            ScreenMeters.OutputCurrentRMS.phA = OutputCurrentRMS.RawRMS.phA;
        }
        // phB
        if ( ScreenMeters.PercentLoadWatts.phB < float( MinLoadForMeterDisplay ) )         // power will be masked out in CalculatePercentLoad() if load off or less than 5%
        {
            ScreenMeters.OutputCurrentRMS.phB = 0.0;
            ScreenMeters.OutputPower.phB = 0.0;
            ScreenMeters.OutputVoltAmperes.phB = 0.0;
            ScreenMeters.BypassCurrentRMS.phB = 0.0;
        }
        else
        {
            ScreenMeters.OutputPower.phB = ( LoadPower.ActivePowerFiltered.phB > 0 ) ? LoadPower.ActivePowerFiltered.phB : 0;
            ScreenMeters.OutputVoltAmperes.phB = ( LoadPower.TotalPowerFiltered.phB > LoadPower.ActivePowerFiltered.phB ) ? LoadPower.TotalPowerFiltered.phB : LoadPower.ActivePowerFiltered.phB;      
            ScreenMeters.OutputCurrentRMS.phB = OutputCurrentRMS.RawRMS.phB;
        }
        // phC
        if ( ScreenMeters.PercentLoadWatts.phC < float( MinLoadForMeterDisplay ) )         // power will be masked out in CalculatePercentLoad() if load off or less than 5%
        {
            ScreenMeters.OutputCurrentRMS.phC = 0.0;
            ScreenMeters.OutputPower.phC = 0.0;
            ScreenMeters.OutputVoltAmperes.phC = 0.0;
            ScreenMeters.BypassCurrentRMS.phC = 0.0;
        }
        else
        {
            ScreenMeters.OutputPower.phC = ( LoadPower.ActivePowerFiltered.phC > 0 ) ? LoadPower.ActivePowerFiltered.phC : 0;
            ScreenMeters.OutputVoltAmperes.phC = ( LoadPower.TotalPowerFiltered.phC > LoadPower.ActivePowerFiltered.phC ) ? LoadPower.TotalPowerFiltered.phC : LoadPower.ActivePowerFiltered.phC;      
            ScreenMeters.OutputCurrentRMS.phC = OutputCurrentRMS.RawRMS.phC;
        }
    } 
    
         // bypass power, kVA = 0 if not on bypass, otherwise = output power,kVA
    if ( NB_GetNodebit( UPM_NB_UPS_ON_BYPASS ) && 
         !NB_GetNodebit( UPM_NB_IN_EASY_CAPACITY_TEST_MODE) )
    {
        ScreenMeters.OutputCurrentRMS = ScreenMeters.BypassCurrentRMS;
    
        ScreenMeters.BypassPower = ScreenMeters.OutputPower;
        ScreenMeters.BypassVoltAmperes = ScreenMeters.OutputVoltAmperes;
        ScreenMeters.BypassPowerFactor = ScreenMeters.OutputPowerFactor;
    
        //ScreenMeters.BypassPower.UpdateSum();
        //ScreenMeters.BypassVoltAmperes.UpdateSum();
    }
    else if ( NB_GetNodebit( UPM_NB_IN_EASY_CAPACITY_TEST_MODE ) )
    {
        ScreenMeters.BypassPower.phA = BypassPower.ActivePowerFiltered.phA;
        ScreenMeters.BypassPower.phB = BypassPower.ActivePowerFiltered.phB;
        ScreenMeters.BypassPower.phC = BypassPower.ActivePowerFiltered.phC;
    
        ScreenMeters.BypassVoltAmperes.phA = BypassPower.TotalPowerFiltered.phA;
        ScreenMeters.BypassVoltAmperes.phB = BypassPower.TotalPowerFiltered.phB;
        ScreenMeters.BypassVoltAmperes.phC = BypassPower.TotalPowerFiltered.phC;
    

		ScreenMeters.OutputPower.phA = LoadPower.ActivePowerFiltered.phA;
		ScreenMeters.OutputPower.phB = LoadPower.ActivePowerFiltered.phB;
		ScreenMeters.OutputPower.phC = LoadPower.ActivePowerFiltered.phC;

		ScreenMeters.OutputVoltAmperes.phA = LoadPower.TotalPowerFiltered.phA; 
		ScreenMeters.OutputVoltAmperes.phB = LoadPower.TotalPowerFiltered.phB; 
		ScreenMeters.OutputVoltAmperes.phC = LoadPower.TotalPowerFiltered.phC; 

		ScreenMeters.OutputCurrentRMS.phA = OutputCurrentRMS.RawRMS.phA;
		ScreenMeters.OutputCurrentRMS.phB = OutputCurrentRMS.RawRMS.phB;
		ScreenMeters.OutputCurrentRMS.phC = OutputCurrentRMS.RawRMS.phC;
    }
    else if ( NB_GetNodebit( UPM_NB_IN_HIGH_EFFICIENCY_MODE ) )
    {
        ScreenMeters.BypassPower = ScreenMeters.OutputPower;
        ScreenMeters.BypassVoltAmperes = ScreenMeters.OutputVoltAmperes;
        ScreenMeters.BypassPowerFactor = ScreenMeters.OutputPowerFactor;
    }
    else 
    {
        // zero out if we're not on bypass
        ScreenMeters.BypassPower = ZeroPower;
        ScreenMeters.BypassVoltAmperes = ZeroPower;
        ScreenMeters.BypassPowerFactor = 0;
    
        //ScreenMeters.OutputCurrentRMS = OutputCurrentRMS.RawRMS;
    }
    
    ScreenMeters.BypassPower.UpdateSum();
    ScreenMeters.BypassVoltAmperes.UpdateSum();
    ScreenMeters.OutputPower.UpdateSum();        
    

    // DC meters
    ScreenMeters.DCLinkVoltage = ( DCLinkVoltagePositive.SlowFiltered - DCLinkVoltageNegative.SlowFiltered );

//	    float BatteryCurrTemp = BatteryCurrentPos.SlowFiltered + BatteryCurrentNeg.SlowFiltered;
	float BatteryCurrTemp = 0.0f;
	if(BatteryCurrentPos.SlowFiltered > BatteryCurrentNeg.SlowFiltered)
	{
		BatteryCurrTemp = BatteryCurrentPos.SlowFiltered;
	}
	else
	{
		BatteryCurrTemp = BatteryCurrentNeg.SlowFiltered;
	}

    if ( NB_GetNodebit( UPM_NB_BATTERIES_DISCONNECTED ) ||
         !NB_GetNodebit(UPM_NB_BATTERY_INSTALLED))
    {
        ScreenMeters.BatteryVoltage = 0.0f; 
        ScreenMeters.BatteryVoltagePos = 0.0f;
        ScreenMeters.BatteryVoltageNeg = 0.0f;
        ScreenMeters.BatteryCurrent = 0.0f;
        ScreenMeters.BatteryCurrentP_Sum = 0.0f;
        ScreenMeters.BatteryCurrentN_Sum = 0.0f;        
        ScreenMeters.CalculatedBTR = 0.0f;
        ScreenMeters.PercentBatteryRemaining = 0.0f;    
    }
    else
    {
    	ScreenMeters.BatteryVoltage = BatteryVoltage.SlowFiltered;
    	ScreenMeters.BatteryVoltagePos = BatteryVoltagePos.SlowFiltered;
        ScreenMeters.BatteryVoltageNeg = BatteryVoltageNeg_SlowFiltered;

        if ( NB_GetNodebit( UPM_NB_BATTERY_CONTACTOR_OPEN ) )
        {
            ScreenMeters.CalculatedBTR =  0.0f;
            ScreenMeters.PercentBatteryRemaining = 0.0f;
            ScreenMeters.BatteryCurrent = 0.0f;
	        ScreenMeters.BatteryCurrentP_Sum = 0.0f;
	        ScreenMeters.BatteryCurrentN_Sum = 0.0f;			
        }
        else
        {
            ScreenMeters.CalculatedBTR =  BTR.BatteryTimeLeft;
            ScreenMeters.PercentBatteryRemaining = 100 * BTR.BatteryTimeLeft / BTR.FullCapacityBTR;
        
            if ( ABM_DISCHARGING == Abm().GetState() )
            {
                ScreenMeters.BatteryCurrent = ( BatteryCurrentPos_Sum_SlowFilter < 0 ) ? BatteryCurrentPos_Sum_SlowFilter : 0.0f;
				ScreenMeters.BatteryCurrentP_Sum = BatteryCurrentPos_Sum_SlowFilter;
				ScreenMeters.BatteryCurrentN_Sum = BatteryCurrentNeg_Sum_SlowFilter;							
            }
            else
            {
                if ( ( ABM_CHARGE == Abm().GetState() ) || ( ABM_FLOAT == Abm().GetState() ) )
                {
				   ScreenMeters.BatteryCurrent = ( BatteryCurrTemp > 0 ) ? BatteryCurrTemp : 0.0f;	//only legA
				   ScreenMeters.BatteryCurrentP_Sum = ( BatteryCurrentPos.SlowFiltered > 0 ) ? BatteryCurrentPos.SlowFiltered : 0.0f;
				   ScreenMeters.BatteryCurrentN_Sum = ( BatteryCurrentNeg.SlowFiltered > 0 ) ? BatteryCurrentNeg.SlowFiltered : 0.0f;				   
                }
                else
                {
                    ScreenMeters.BatteryCurrent = 0.0f;    
					ScreenMeters.BatteryCurrentP_Sum = 0.0f;
					ScreenMeters.BatteryCurrentN_Sum = 0.0f;					
                }
            }
        }
    }

    // frequencies
    ScreenMeters.InputFrequency = Rectifier.UtilityPLL.GetFrequency();
    ScreenMeters.BypassFrequency = BypassPLL.GetFrequency();
    ScreenMeters.OutputFrequency = OutputPLL.GetFrequency();
    ScreenMeters.InverterFrequency = Inverter.GetFrequency();
    
    // Calculated values based on other meters.
    ScreenMeters.InputVoltAmperes.phA = ScreenMeters.InputVoltageRMS.phA * ScreenMeters.InputCurrentRMS.phA;
    ScreenMeters.InputVoltAmperes.phB = ScreenMeters.InputVoltageRMS.phB * ScreenMeters.InputCurrentRMS.phB;
    ScreenMeters.InputVoltAmperes.phC = ScreenMeters.InputVoltageRMS.phC * ScreenMeters.InputCurrentRMS.phC;
    
    
    ScreenMeters.InputVoltAmperes.UpdateSum();      
    ScreenMeters.OutputVoltAmperes.UpdateSum();
        
    // power factor can't be greater than 1
    if ( ScreenMeters.InputPower.sum > ScreenMeters.InputVoltAmperes.sum )
    {
        ScreenMeters.InputPower.sum = ScreenMeters.InputVoltAmperes.sum;
    }                                                 
    ScreenMeters.InputPowerFactor = ScreenMeters.InputPower.sum / ScreenMeters.InputVoltAmperes.sum;  
    
    if ( ScreenMeters.OutputPower.sum > ScreenMeters.OutputVoltAmperes.sum )
    {
        ScreenMeters.OutputPower.sum = ScreenMeters.OutputVoltAmperes.sum;
    }    

    float ReactiveCapacitance = PFfiltergain * ScreenMeters.OutputFrequency * 2.0f * PI * InverterCap / 2.0f;
    CapCurrentAdj.phA = ReactiveCapacitance * ScreenMeters.OutputVoltageRMS.phA;
    CapCurrentAdj.phB = ReactiveCapacitance * ScreenMeters.OutputVoltageRMS.phB;
    CapCurrentAdj.phC = ReactiveCapacitance * ScreenMeters.OutputVoltageRMS.phC;

    if ((AvgAmpsOutVar.phA - CapCurrentAdj.phA) < -16.0f)
    {
        indCurrentLimit.phA = 16.0f;
    }
    if ((AvgAmpsOutVar.phB - CapCurrentAdj.phB) < -16.0f)
    {
        indCurrentLimit.phB = 16.0f;
    }
    if ((AvgAmpsOutVar.phC - CapCurrentAdj.phC) < -16.0f)
    {
        indCurrentLimit.phC = 16.0f;
    }

    if ((AvgAmpsOutVar.phA - CapCurrentAdj.phA) > 16.0f)
    {
        indCurrentLimit.phA = -16.0f;
    }
    if ((AvgAmpsOutVar.phB - CapCurrentAdj.phB) > 16.0f)
    {
        indCurrentLimit.phB = -16.0f;
    }
    if ((AvgAmpsOutVar.phC - CapCurrentAdj.phC) > 16.0f)
    {
        indCurrentLimit.phC = -16.0f;
    }

    AvgAmpsOutVar.phA = (7.0f/8.0f)*AvgAmpsOutVar.phA + OutputReactiveAmps.phA;
    AvgAmpsOutVar.phB = (7.0f/8.0f)*AvgAmpsOutVar.phB + OutputReactiveAmps.phB;
    AvgAmpsOutVar.phC = (7.0f/8.0f)*AvgAmpsOutVar.phC + OutputReactiveAmps.phC;
    
    if ( ( AvgAmpsOutVar.phA + AvgAmpsOutVar.phB + AvgAmpsOutVar.phC - 
         ( CapCurrentAdj.phA + CapCurrentAdj.phB + CapCurrentAdj.phC ) ) <
       ( indCurrentLimit.phA + indCurrentLimit.phB + indCurrentLimit.phC ) )
    {
        //PF > 1, load type is inductor
        ScreenMeters.OutputPowerFactor = ScreenMeters.OutputPower.sum / ScreenMeters.OutputVoltAmperes.sum + 1;
    }
    else
    {
        ScreenMeters.OutputPowerFactor = ScreenMeters.OutputPower.sum / ScreenMeters.OutputVoltAmperes.sum;
    }

    if ( ScreenMeters.BypassPower.sum > ScreenMeters.BypassVoltAmperes.sum )
    {
        ScreenMeters.BypassPower.sum = ScreenMeters.BypassVoltAmperes.sum;
    }                                                 
    ScreenMeters.BypassPowerFactor = ScreenMeters.BypassPower.sum / ScreenMeters.BypassVoltAmperes.sum;                                                

    ScreenMeters.BatteryVPC = ScreenMeters.BatteryVoltage / NumberOfBatteryCells;        

    
    // Set rating meters.
    ScreenMeters.OutputVoltageRating = (float)OutNomVolts / 10;
    ScreenMeters.InputVoltageRating = ScreenMeters.OutputVoltageRating;
    ScreenMeters.InputVoltageMinRating = 0.9*ScreenMeters.InputVoltageRating;
    ScreenMeters.InputVoltageMaxRating = UtilityMaxRMSLimit;
    ScreenMeters.OutputFrequencyRating = OutNomFreq;
    ScreenMeters.InputFrequencyRating = ScreenMeters.OutputFrequencyRating;
    ScreenMeters.OutputPowerFactorRating = (float)OutputPowerFactorRating / 10000;
    ScreenMeters.OutputkVARating = (float)OutputkVARating * 100;
    ScreenMeters.BatteryTimeRating = BatteryTimeRating;
    ScreenMeters.BatteryLoadRating = 100;
    
}

// ***********************************************************************
// *
// *    FUNCTION: CalculatePercentLoad 
// *
// *    DESCRIPTION: Calculates max or percent kVA or percent kW 
// *
// *    ARGUMENTS: 
// *
// *    RETURNS: 
// *
// ***********************************************************************
static void CalculatePercentLoad( void )
{
    if ( NB_GetNodebit( UPM_NB_LOAD_POWER_OFF ) )
    {
        ScreenMeters.PercentLoad = ZeroPower;
        ScreenMeters.PercentLoadWatts = ZeroPower;
        ScreenMeters.PercentLoadVA = ZeroPower;
    }
    else
    {       
        // outkVA and outW are stored as int, kW(VA) * 10
        // Be careful that when in bypass state, only UPM0 controls the STS.
        float percentWattsFactor;
        float percentVAFactor;
        
	    if( MCUStateMachine.BypassSupportingLoad() )
	    {
	        percentWattsFactor = 100.0 / (float)( OutputkWRating  * 100uL * NumOfModule );
	        percentVAFactor    = 100.0 / (float)( OutputkVARating * 100uL * NumOfModule );
	    }
	    else
	    {
            percentWattsFactor = 100.0 / (float)( OutputkWRating * 100uL );
            percentVAFactor    = 100.0 / (float)( OutputkVARating * 100uL );
	    }
         
        // total first
        ScreenMeters.PercentLoadWatts.sum = LoadPower.ActivePowerFiltered.sum * percentWattsFactor;
        ScreenMeters.PercentLoadVA.sum    = LoadPower.TotalPowerFiltered.sum * percentVAFactor;
        
        percentWattsFactor *= 3.0;
        percentVAFactor    *= 3.0;
        ScreenMeters.PercentLoadWatts.phA = LoadPower.ActivePowerFiltered.phA * percentWattsFactor;
        ScreenMeters.PercentLoadWatts.phB = LoadPower.ActivePowerFiltered.phB * percentWattsFactor;
        ScreenMeters.PercentLoadWatts.phC = LoadPower.ActivePowerFiltered.phC * percentWattsFactor;
        ScreenMeters.PercentLoadVA.phA    = LoadPower.TotalPowerFiltered.phA * percentVAFactor;
        ScreenMeters.PercentLoadVA.phB    = LoadPower.TotalPowerFiltered.phB * percentVAFactor;
        ScreenMeters.PercentLoadVA.phC    = LoadPower.TotalPowerFiltered.phC * percentVAFactor;
        
        // zero out everything if percent load is less than 5%
        // if ( ScreenMeters.PercentLoadWatts.sum < 5.0f )         // power will be masked out in CalculatePercentLoad() if load off or less than 5%
        if ( ( abs(ScreenMeters.PercentLoadWatts.phA) < float( MinLoadForMeterDisplay ) ) &&
             ( abs(ScreenMeters.PercentLoadWatts.phB) < float( MinLoadForMeterDisplay ) ) &&
             ( abs(ScreenMeters.PercentLoadWatts.phC) < float( MinLoadForMeterDisplay ) ) )
        {
            ScreenMeters.PercentLoad = ZeroPower;
            ScreenMeters.PercentLoadVA = ZeroPower;
            ScreenMeters.PercentLoadWatts = ZeroPower;
        }
        else
        {
            // take the greater of the 2
            if ( abs(ScreenMeters.PercentLoadWatts.sum) > ScreenMeters.PercentLoadVA.sum )
            {
                ScreenMeters.PercentLoad.sum = abs(ScreenMeters.PercentLoadWatts.sum);
            }
            else
            {
                ScreenMeters.PercentLoad.sum = ScreenMeters.PercentLoadVA.sum;
            }

            //phA
            // take the greater of the 2
            if ( abs(ScreenMeters.PercentLoadWatts.phA) > ScreenMeters.PercentLoadVA.phA )
            {
                ScreenMeters.PercentLoad.phA = abs(ScreenMeters.PercentLoadWatts.phA);
            }
            else
            {
                ScreenMeters.PercentLoad.phA = ScreenMeters.PercentLoadVA.phA;
            }
            //phB
            // take the greater of the 2
            if ( abs(ScreenMeters.PercentLoadWatts.phB) > ScreenMeters.PercentLoadVA.phB )
            {
                ScreenMeters.PercentLoad.phB = abs(ScreenMeters.PercentLoadWatts.phB);
            }
            else
            {
                ScreenMeters.PercentLoad.phB = ScreenMeters.PercentLoadVA.phB;
            }
            //phC
            // take the greater of the 2
            if ( abs(ScreenMeters.PercentLoadWatts.phC) > ScreenMeters.PercentLoadVA.phC )
            {
                ScreenMeters.PercentLoad.phC = abs(ScreenMeters.PercentLoadWatts.phC);
            }
            else
            {
                ScreenMeters.PercentLoad.phC = ScreenMeters.PercentLoadVA.phC;
            }
        }
    }
}

/*
 * Divide an stAC_Power object as a three-vector quantity by a scalar.
 */
stAC_Power operator/(const stAC_Power& lhs, float divisor)
{
    stAC_Power ret = lhs;
    float inverse = 1.0f/divisor;
    ret.phA *= inverse;
    ret.phB *= inverse;
    ret.phC *= inverse;
    ret.UpdateSum();
    return ret;
} 

// ****************************************************************************
// *            END OF ProcessAC.c
// ****************************************************************************
