// ****************************************************************************
// *             Parameters.h
// ****************************************************************************
// ****************************************************************************
// *
// * THIS INFORMATION IS PROPRIETARY TO Eaton Corporation
// *
// ****************************************************************************
// *
// *  Copyright (c) 2009 Eaton Corporation
// *    ALL RIGHTS RESERVED
// *
// ****************************************************************************
// ****************************************************************************
// *    FILE NAME:   Parameters.h
// *
// *    DESCRIPTION: 
// *
// *    ORIGINATOR:  Tuomo Kaikkonen
// *
// *    DATE:        2009-03-04
// *
// *    HISTORY: See revision control system's history.
// ****************************************************************************

#ifndef PARAMETERS_H
#define PARAMETERS_H

typedef enum parameter_t
{
    PARAM_NULL                              = 0,

    PARAM_MyUPSNumber                       = 3,
    PARAM_ExtSyncEnabled                    = 6,
    PARAM_UPMCalEnabled                     = 7,
    PARAM_ParallelForRedundancy             = 8,
    PARAM_NumOfUPSs                         = 9,
    PARAM_FirstTimeRun                      = 10,
    PARAM_SystemType                        = 11,
    PARAM_NumOfModule                       = 12,
    PARAM_NewCtrlBoard                      = 13,
    
    PARAM_BypassWithNormal                  = 51,
    PARAM_EPOToBypass                       = 52,
    PARAM_OutNomVolts                       = 53,
    PARAM_OutFrequency                      = 54,
    PARAM_BypACOVLevel                      = 55,
    PARAM_BypACUVLevel                      = 56,
    PARAM_InvSyncLim                        = 57,
    PARAM_BattNotRequired                   = 58,
    PARAM_EnableAutoStandby                 = 59,
    PARAM_EnableAutoRestart                 = 60,
    PARAM_AutoRestart                       = 61,
    PARAM_ESSInstalled                      = 62,
    PARAM_ESSMaxNumOutages                  = 63,
    PARAM_ESSOutageResetTime                = 64,
    PARAM_ESSLockoutTime                    = 65,
    PARAM_STSWshortCurrentPercent           = 66,
    PARAM_EPOEnabled                        = 67,           
    PARAM_MBSInstalled                      = 68,
    PARAM_SetupRequired                     = 69,
    PARAM_InputSyncEnabled                  = 70,
    PARAM_BackfeedContactorInstalled        = 71,
    PARAM_InternalBatteryBreakerInstalled   = 72,   // Pan/20120914
    PARAM_EnableOpenLoop                    = 73,   //Vayn/20150323 add
    PARAM_ATBEnabled                        = 74,
    PARAM_ATBFixedDelay                     = 75,
    PARAM_ATBBypassCMDEnable                = 76,
    PARAM_PowerConditionerMode              = 77,
    PARAM_ECTSineRefForwardEnabled          = 78,
    PARAM_ECTRectifier_Sine_Ref_Gain        = 79,
    PARAM_OutPF                             = 80,
    PARAM_OutKVA_Obsolete                   = 81,
    PARAM_InverterShortCurrentLimit         = 82,
    PARAM_InverterShortCurrentLimitCycles   = 83,
    PARAM_DisableImmBypassTransfer          = 84,
    PARAM_ImmBypassTransferDelay            = 85,
    PARAM_DisableTooManyBatTrans            = 86,
    PARAM_ParallelLoadShareErrorLimit       = 87,
    PARAM_EnableVFMode                      = 88,
    PARAM_VFModeLoadPercentMax              = 89,
    PARAM_VFModeLoadPercentHysteresis       = 90,
    PARAM_VFModeEntryTime                   = 91,
	PARAM_BypACOVFastLevel					= 92,
	PARAM_BypACUVFastLevel					= 93,
	PARAM_OpACUVActiveTime					= 94,
	
	PARAM_ESSOutputSdLowTime				= 96,
	PARAM_Unit_Setup1					    = 97,

    PARAM_Bal_Relay_Time                    = 100,
    PARAM_L1_Relay_Time                     = 101,
    PARAM_Batt_Relay_Time                   = 102,
    PARAM_DCLinkStepMax                     = 103,
	PARAM_InputHighLimit					= 104,
	PARAM_RecHighLimit						= 105,
	PARAM_RectiferCurrentMargin				= 106,
	PARAM_K1MaxTimeToOpen					= 107,
	PARAM_BalMaxTimeToOpen					= 108,	
	PARAM_OpACUVFastLevel					= 109,
	PARAM_OpACUVFastMinLevel			    = 110,
	PARAM_ESSBypACUVFastLevel				= 111,
	PARAM_BypACUVActiveTime					= 112,
	PARAM_DClinkDelta						= 113,
	PARAM_DCPreChargeRailLimit              = 114,
	PARAM_PrechargeType                     = 115,
	PARAM_PrechargeTime                     = 116,
    PARAM_InputCapCompRef                   = 117,
    PARAM_NegPowerLimit                     = 118,
	PARAM_SineRefForwardEnabled             = 119,
    PARAM_Rectifer_DCLink_Set               = 120,
    PARAM_RectifierCurrentMax               = 121,
    PARAM_RectifierGenCurrentMax            = 122,
    PARAM_RectifierWalkinRate               = 123,
    Param_OutputPLLMaxPhaseError            = 124,
    PARAM_Rectifier_Sine_Ref_Gain           = 125,
    PARAM_OptimizeInputPFEnabled            = 126,
    PARAM_UtilityPLLAngleOffset             = 127,
    PARAM_SineRefGain                       = 128,
    PARAM_MinLoadForMeterDisplay            = 129,
    PARAM_RectifierWalkinDelay              = 130,
    PARAM_BypassPLLMaxPhaseError            = 131,
    PARAM_RectifierVoltageLoopGain			= 132,
	PARAM_RectifierCurrentLoopGain			= 133,   
	PARAM_BypassPLLMinDQ					= 134,
	PARAM_EnableTransferBatDCF				= 135,
	
	PARAM_InvControlParaOption              = 139,
    PARAM_InverterSlewRate                  = 140,
    PARAM_InverterSWCurrentLim              = 141,
    PARAM_InverterUVSetLevel                = 142,
    PARAM_InverterUVClearLevel              = 143,
    PARAM_BypassPhaseOffset                 = 144,
    PARAM_UtilityPhaseOffset                = 145,
    PARAM_OutputPhaseOffset                 = 146,
    PARAM_BasePhaseOffset                   = 147,
    PARAM_BypassLoadSharePhaseCal           = 148,
    PARAM_UtilityLoadSharePhaseCal          = 149,
    PARAM_OutputLoadSharePhaseCal           = 150,
    PARAM_BaseLoadSharePhaseCal             = 151,
    PARAM_LoadShareVoltageCalA              = 152,
    PARAM_LoadShareVoltageCalB              = 153,
    PARAM_LoadShareVoltageCalC              = 154,
    PARAM_DCcomponentOffsetA                = 155,
    PARAM_DCcomponentOffsetB                = 156,
    PARAM_DCcomponentOffsetC                = 157,
    PARAM_SyncConfiguration                 = 158,
    PARAM_UnitConfiguration                 = 159,
    PARAM_DaylightSavingsTime               = 160,
    PARAM_HistoryTrigger                    = 161,
    PARAM_DeadTimeConfig                    = 162,
    PARAM_DCLinkRampCurrent					= 163,
    PARAM_EnableDeadTimeCompensate			= 165,
	PARAM_EnablePullChainChk				= 167,
	PARAM_EEEPODelay						= 168,
    PARAM_MinReqkVA                         = 169,
	PARAM_InverterVoltLoopGain				= 170,	 
	PARAM_BatChargeCurrLoopGain				= 171,	     
	PARAM_InvEctCurrLoopGain				= 172,
	PARAM_DriverFaultMaxNumOutages			= 173,
    PARAM_EnableParalPwmSync                = 174,
    PARAM_FrequencyConverterMode            = 175,
    PARAM_InverterCurrLoopGain              = 176,
    PARAM_RecThdiImprove                    = 177,
    PARAM_InvDutyCompensation     			= 192,
    PARAM_FeedForwardGain                   = 193,
    PARAM_DelayCount                        = 194,
    PARAM_AbsDCOVSet                        = 201,
    PARAM_AbsDCUVSet                        = 202,
    PARAM_CurrLimOffMaxInv                  = 203,
    PARAM_CurrLimOffMaxRect                 = 204,
    PARAM_CurrLimOffMaxBatt                 = 205,
    PARAM_OvrldLowPercent                   = 206,
    PARAM_OvrldLowTime                      = 207,
    PARAM_OvrldMedPercent                   = 208,
    PARAM_OvrldMedTime                      = 209,
    PARAM_OvrldHiPercent                    = 210,
    PARAM_OvrldHiTime                       = 211,
    PARAM_OvrldXtrmPercent                  = 212,
    PARAM_OvrldXtrmTime                     = 213,
    
    PARAM_InpACOVLevel                      = 214,
    PARAM_InpACUVLevel                      = 215,
    PARAM_Inverter_Current_Limit_Set        = 216,
    PARAM_Rectifier_Current_Limit_Set       = 217,
    PARAM_Battery_Current_Limit_Set         = 218,
    PARAM_PhaseAHeatsinkOTWarning           = 219,
    PARAM_PhaseAHeatsinkOTTrip              = 220,
    PARAM_AmbientTempLimit                  = 221,
    PARAM_LogicPower5v                      = 222,          
    PARAM_LogicPower15v                     = 223,
    PARAM_InputFreqLowLimit                 = 224,
    PARAM_InputFreqHighLimit                = 225,
    PARAM_ACPreChargeRailLimit              = 226,
    PARAM_DisableSiteWiringFault            = 227,
    PARAM_SiteWiringFaultHighLimit          = 228,
    PARAM_BackfeedRelayFailSetting          = 229,
    PARAM_ESSEnabled                        = 230,
    PARAM_DisableRevisionCheck              = 231,
    PARAM_SelectiveTripDQLimit              = 232,
    PARAM_SelectiveTripVDiffLimit           = 233,
    PARAM_EnableDisChargeLink               = 234,
    PARAM_DisChargeLinkVoltage              = 235,
	PARAM_FanInputAmpsRMSLevel_1			= 239,
	PARAM_FanInputAmpsRMSLevel_2			= 240,
	PARAM_FanInputAmpsRMSLevel_3			= 241,
	PARAM_FanInputAmpsRMSHysteresis			= 242,
	PARAM_FanFailTempPrtDec					= 243,
	PARAM_HeatsinkTempFanFull				= 244,
	PARAM_AutoEctEnable						= 245,
	PARAM_DiffVoltInvOutRms_X10				= 246,
	PARAM_PhaseBHeatsinkOTWarning			= 247,
	PARAM_PhaseBHeatsinkOTTrip				= 248,
	PARAM_BatHeatsinkOTWarning				= 249,
	PARAM_BatHeatsinkOTTrip					= 250,
	PARAM_RecFanFailTempPrtDec				= 251,
	PARAM_BatFanFailTempPrtDec				= 252,
	PARAM_InvHeatsinkTempFanFull			= 253,
    PARAM_FuseFailLoadPercentLimit          = 254,
    PARAM_UtilityLossPercentLimit           = 255,
    PARAM_BackfeedRlyOpenFailSetting		= 256,
    
    PARAM_AdapAMBTempLimit                  = 261,
    PARAM_AdapAMBTempHyst                   = 262,
    PARAM_AOLEnable                         = 263,
    PARAM_AdapOvrldLowTime                  = 264,
    PARAM_AdapOvrldMedTime                  = 265,
    PARAM_AdapOvrldHiTime                   = 266,
    PARAM_AdapOvrldXtrmTime                 = 267,
    PARAM_UPSPowerShareBuffer               = 268,
    PARAM_MAXFanSpeed                       = 269,
    PARAM_FanFailLimt                       = 270,
    PARAM_WalkinStartPercentLoad            = 271,    
	PARAM_PhaseCHeatsinkOTWarning				= 272,
  	PARAM_KeepAlive_Delay					= 273,
    PARAM_SCRHeatsinkOTWarning              = 274,
    PARAM_SCRHeatsinkOTTrip                 = 275,
    PARAM_InvCapHeatsinkOTWarning           = 276,
    PARAM_InvCapHeatsinkOTTrip              = 277,
	PARAM_RelDCUVSet						= 278,
	//279-280 reserved for load sync
	PARAM_SingleUPSStartUpEnabled           = 281,

    PARAM_NumCells                          = 302,
    PARAM_NumStrings                        = 303,
    PARAM_Batt_ChrgCurrent                  = 304,    
    PARAM_batChargeTMax                     = 305,
    PARAM_batFloatTime                      = 306,
    PARAM_batMaxRestT                       = 307,
    PARAM_batMinDischT                      = 308,
    PARAM_batRestFailT                      = 309,
    PARAM_batMaxChrgCurrentforESS           = 310,
    PARAM_Batt_ChargeV_PerCell              = 311,
    PARAM_Batt_ConstFloatV_PerCell          = 312,
    PARAM_batOpChrgCellV                    = 314,
    PARAM_BattTestFailVLow                  = 315,
    PARAM_BattTestFailVHigh                 = 316,
    PARAM_QueOnBattery                      = 317,
    PARAM_Batt_OV_Time                      = 318,
    PARAM_LowBatteryWarnLimit               = 319,
    PARAM_Batt_UV_PerCell                   = 320,
    PARAM_Batt_UV_Absolute_PerCell          = 321,
    PARAM_Batt_OV_PerCell                   = 322,   

    PARAM_MinInputForCharging               = 324,  
    PARAM_HRDBattTimeIntercept              = 325,
    PARAM_HRDBattTimeSlope                  = 326,
    PARAM_LRDBattTimeIntercept              = 327,
    PARAM_LRDBattTimeSlope                  = 328, 
    PARAM_BatteryType                       = 329,  
    PARAM_KeepAlive_BatUVPC                 = 330,
    PARAM_BatteryAhRating                   = 331, 
    PARAM_BatteryTimeRating                 = 332,
    PARAM_WattsPerCell15Min                 = 333,
    PARAM_WattsPerCell60Min                 = 334,   
    PARAM_BatteryTest1Time                  = 335,
    PARAM_BatteryTest2Time                  = 336,
    PARAM_CommissioningTest                 = 337,
    PARAM_CommonBattery                     = 338,
    PARAM_ABMDisabled                       = 339,  //Jacob/20130823/add
    PARAM_WattsPerCellUnits                 = 340,  //Jack/20150108/add
    PARAM_Compensate_Rate                   = 341,
    PARAM_NumExternalStrings                = 350,  // Pan/20120914

	PARAM_Battery_disconnect_VPC			= 354,
	PARAM_BattRelayOpenCurrent              = 355,
	PARAM_ESSChrgCurrentOffsetCal           = 356,
    // calibration section, in order of A/D channel, not sample order!!

    // A/D channels 0-5, fast channels mux x2
    PARAM_ADC_CH0_0_CAL                     = 419,
    PARAM_ADC_CH0_1_CAL                     = 407,
    PARAM_ADC_CH1_0_CAL                     = 420,
    PARAM_ADC_CH1_1_CAL                     = 408,
    PARAM_ADC_CH2_0_CAL                     = 421,
    PARAM_ADC_CH2_1_CAL                     = 409,
    PARAM_ADC_CH3_0_CAL                     = 413,
    PARAM_ADC_CH3_1_CAL                     = 401,
    PARAM_ADC_CH4_0_CAL                     = 414,
    PARAM_ADC_CH4_1_CAL                     = 402,
    PARAM_ADC_CH5_0_CAL                     = 415,
    PARAM_ADC_CH5_1_CAL                     = 403,

    // A/D channel 6, medium channel mux x4
    PARAM_ADC_CH6_0_CAL                     = 425,
    PARAM_ADC_CH6_1_CAL                     = 427,
    PARAM_ADC_CH6_2_CAL                     = 429,
    PARAM_ADC_CH6_3_CAL                     = 431,

    // A/D channel 7, slow channel mux x8
    PARAM_ADC_CH7_0_CAL                     = 434,
    PARAM_ADC_CH7_1_CAL                     = 436,
    PARAM_ADC_CH7_2_CAL                     = 438,
    PARAM_ADC_CH7_3_CAL                     = 440,
    PARAM_ADC_CH7_4_CAL                     = 442,
    PARAM_ADC_CH7_5_CAL                     = 444,
    PARAM_ADC_CH7_6_CAL                     = 446,
    PARAM_ADC_CH7_7_CAL                     = 448,

    // A/D channels 8-13, fast channels mux x2
    PARAM_ADC_CH8_0_CAL                     = 416,
    PARAM_ADC_CH8_1_CAL                     = 404,
    PARAM_ADC_CH9_0_CAL                     = 417,
    PARAM_ADC_CH9_1_CAL                     = 405,
    PARAM_ADC_CH10_0_CAL                    = 418,
    PARAM_ADC_CH10_1_CAL                    = 406,
    PARAM_ADC_CH11_0_CAL                    = 422,
    PARAM_ADC_CH11_1_CAL                    = 410,
    PARAM_ADC_CH12_0_CAL                    = 423,
    PARAM_ADC_CH12_1_CAL                    = 411,
    PARAM_ADC_CH13_0_CAL                    = 424,
    PARAM_ADC_CH13_1_CAL                    = 412,

    // A/D channel 14, medium channel mux x4
    PARAM_ADC_CH14_0_CAL                    = 426,
    PARAM_ADC_CH14_1_CAL                    = 428,
    PARAM_ADC_CH14_2_CAL                    = 430,
    PARAM_ADC_CH14_3_CAL                    = 432,

    // A/D channel 15, slow channel mux x8
    PARAM_ADC_CH15_0_CAL                    = 433, 
    PARAM_ADC_CH15_1_CAL                    = 435, 
    PARAM_ADC_CH15_2_CAL                    = 437, 
    PARAM_ADC_CH15_3_CAL                    = 439, 
    PARAM_ADC_CH15_4_CAL                    = 441, 
    PARAM_ADC_CH15_5_CAL                    = 443, 
    PARAM_ADC_CH15_6_CAL                    = 445, 
    PARAM_ADC_CH15_7_CAL                    = 447,

//1.New cal index in hobbit for hw ad channel change
    PARAM_CAL_BatteryVoltageCal             = 407,
	PARAM_CAL_InputVoltageNeutralCal 		= 408,
	PARAM_CAL_AnalogZeroCal					= 433,
	PARAM_CAL_ChassisVoltageCal 			= 443,
	PARAM_CAL_BatteryVoltageChgPosCal		= 445,
	PARAM_CAL_BatteryVoltageChgNegCal		= 446,
	PARAM_CAL_LogicPower15vCal				= 447,
	PARAM_CAL_LogicPower24vCal				= 448,
	//1.2.AD index: uAdcCalibration,  stRawAdcData
    PARAM_CAL_BatteryVoltageCal_AdcIndex     		= 45,
	PARAM_CAL_InputVoltageNeutralCal_AdcIndex 		= 32,
	PARAM_CAL_AnalogZeroCal_AdcIndex				= 1,	
	PARAM_CAL_ChassisVoltageCal_AdcIndex 			= 46,
	PARAM_CAL_BatteryVoltageChgPosCal_AdcIndex		= 6,
	PARAM_CAL_BatteryVoltageChgNegCal_AdcIndex		= 7,
	PARAM_CAL_LogicPower15vCal_AdcIndex				= 42,
	PARAM_CAL_LogicPower24vCal_AdcIndex				= 44,
	PARAM_CAL_BatteryVoltagePosCal_AdcIndex			= 47,
    
    // Section 7 parameters
    PARAM_OutKVA                            = 3501,
    PARAM_SvcRequired                       = 3502,
    PARAM_NumOfUPMs                         = 3503,
    PARAM_MOBEnabled                        = 3504,
    PARAM_DisableAutoID                     = 3505    
    
} parameter_t;

#endif
